from bayes_opt import BayesianOptimization
from sklearn.model_selection import ParameterGrid
import functools
# from bayes_excercise import *
from bayes_kelly import *
import numpy as np
import warnings
from pandas.core.common import SettingWithCopyWarning

warnings.filterwarnings('ignore', category=SettingWithCopyWarning)


def optimize_func(csv_path, **kwargs):
    tparam.update(kwargs)
    debug = kwargs.get('debug', False)

    df = pd.read_csv(csv_path)
    df = df.dropna()
    base_df = df.copy()
    base_df = calc_confidence_betratio(base_df, s_turtle_buy)
    profit_table, w_daily_return, simulate_transaction_df = back_test(base_df, breakdown=False)
    s_summary = profit_table.iloc[0]

    # 胜率 = 获利交易数 / 总交易数
    # win_rate = (simulate_transaction_df['kelly(f)'] > 0).sum() / (simulate_transaction_df['kelly(f)'] <= 0).sum()
    # win_rate = (simulate_transaction_df['kelly(f)'] > 0).sum() / len(simulate_transaction_df['kelly(f)'])

    # win_rate = (s_summary.ProfitSample + 0.001) / (s_summary.Sample + 0.001)
    # profit_loss_ratio = s_summary.ProfitLossRatio
    # profit_loss_ratio = (simulate_transaction_df['kelly(f)'] > 0 & simulate_transaction_df['F.ProfitAmount'] > 0).mean() / (simulate_transaction_df['kelly(f)'] > 0 & simulate_transaction_df['F.ProfitAmount'] < 0).mean()
    # sample_weight = len(simulate_transaction_df) / (len(df) + 2)
    score = s_summary.Profit
    # print(f'{win_rate} * {sample_weight} * {profit_loss_ratio} * {sample_weight} ')
    '''
    # weight
    w_sample = 0.6
    w_profit_ratio = 0.20
    w_max_drawdown = 0.20

    sample = s_summary.Sample + 0.001
    profit_sample = s_summary.ProfitSample + 0.001
    loss_sample = sample - profit_sample
    sample_power = (profit_sample/loss_sample-1) * (sample/365)
    # sample_power = (profit_sample/loss_sample-1) * (sample/365) if (profit_sample and loss_sample) else 0.1

    profit_ratio = s_summary['ProfitRatio'] - 1

    max_drawdown = s_summary.Drawdown if not np.isnan(s_summary.Drawdown) else -1
    score = (w_sample * sample_power) + (w_profit_ratio * profit_ratio) + (w_max_drawdown * max_drawdown)
    '''

    if debug:
        # print(f'Sample power: {profit_sample}/{loss_sample} - 1 * {sample} / 365 ({w_sample * sample_power:.2f}), '
        #       f'profit_ratio: {profit_ratio} ({(w_profit_ratio * profit_ratio):.2f}), '
        #       f'max_drawdown: {max_drawdown:.2f} ({w_max_drawdown*max_drawdown:.2f}), '
        #       f'score: {score:.2f}')
        profit_table.to_csv(f'{bkf._name}_performance.csv', index=False)
        print(profit_table)
        kelly_df.to_csv(f'{bkf._name}_best_kelly.csv', index=False)
        print(f'created: {bkf._name}_best_kelly.csv')
        full_df = pd.merge(bkf._df, simulate_transaction_df, how='left', on=['Date'])
        full_df['TTL_signal'] = full_df.Close > full_df.turtle_h
        full_df.to_csv(f'{bkf._name}_full_df.csv', index=False)
        print(f'created: {bkf._name}_full_df.csv')
    return score


def run():
    run_optimize = 1
    best_params = {'ATR_sample': 67.45465113173290,
                     'atr_loss_margin': 1.2736213988508600,
                     'bayes_windows': 493.7536918075720,
                     'lower_sample': 17.991732615371500,
                     'upper_sample': 76.13170396012780}
    # a = '''1295.KL.csv 4952.KL.csv 5116.KL.csv 5176.KL.csv 5280.KL.csv A68U.SI.csv AW9U.SI.csv C2PU.SI.csv CMOU.SI.csv D07.SI.csv J91U.SI.csv M44U.SI.csv O87.SI.csv RW0U.SI.csv 5099.KL.csv 5120.KL.csv 5180.KL.csv 5347.KL.csv A7RU.SI.csv BMGU.SI.csv C38U.SI.csv CNNU.SI.csv D5IU.SI.csv JYEU.SI.csv ME8U.SI.csv ODBU.SI.csv S27.SI.csv TS0U.SI.csv 1F2.SI.csv 5106.KL.csv 5121.KL.csv 5212.KL.csv 6963.KL.csv ACV.SI.csv BTOU.SI.csv C61U.SI.csv COI.SI.csv D8DU.SI.csv K2LU.SI.csv MXNU.SI.csv OVQ.SI.csv S7OU.SI.csv UD1U.SI.csv 2605.TW.csv 5109.KL.csv 5123.KL.csv 5227.KL.csv 7100.KL.csv ADQU.SI.csv BUOU.SI.csv CEDU.SI.csv CRPU.SI.csv HMN.SI.csv K71U.SI.csv N2IU.SI.csv OXMU.SI.csv SK6U.SI.csv XZL.SI.csv 3182.KL.csv 5110.KL.csv 5127.KL.csv 5235SS.KL.csv 7113.KL.csv AJBU.SI.csv BWCU.SI.csv CJLU.SI.csv CWCU.SI.csv J69U.SI.csv LIW.SI.csv NS8U.SI.csv P40U.SI.csv SV3U.SI.csv 4715.KL.csv 5111.KL.csv 5130.KL.csv 5269.KL.csv A17U.SI.csv AU8U.SI.csv BYJ.SI.csv CLR.SI.csv CY6U.SI.csv J85.SI.csv M1GU.SI.csv O5RU.SI.csv Q5T.SI.csv T82U.SI.csv'''
    # a = '''1295.KL.csv 4952.KL.csv 5116.KL.csv 5176.KL.csv 5280.KL.csv A68U.SI.csv AW9U.SI.csv C2PU.SI.csv CMOU.SI.csv D07.SI.csv J91U.SI.csv M44U.SI.csv O87.SI.csv RW0U.SI.csv 5099.KL.csv 5120.KL.csv 5180.KL.csv'''
    a = '''O87.SI.csv'''
    metas = {
        '1INCH-USD.csv': '1INCH-USD',
        '1SOL-USD.csv': '1SOL-USD',
        'AAC-USD.csv': 'AAC-USD',
        'AAVE-USD.csv': 'AAVE-USD',
        'ABBC-USD.csv': 'ABBC-USD',
        'ABT-USD.csv': 'ABT-USD',
        'ACA-USD.csv': 'ACA-USD',
        'ACH-USD.csv': 'ACH-USD',
        'ACT-USD.csv': 'ACT-USD',
        'ADA-USD.csv': 'ADA-USD',
        'ADP-USD.csv': 'ADP-USD',
        'ADX-USD.csv': 'ADX-USD',
        'AE-USD.csv': 'AE-USD',
        'AEGIS-USD.csv': 'AEGIS-USD',
        'AGIX-USD.csv': 'AGIX-USD',
        'AGLD-USD.csv': 'AGLD-USD',
        'AIOZ-USD.csv': 'AIOZ-USD',
        'AKRO-USD.csv': 'AKRO-USD',
        'AKT-USD.csv': 'AKT-USD',
        'ALGO-USD.csv': 'ALGO-USD',
        'ALI-USD.csv': 'ALI-USD',
        'ALICE-USD.csv': 'ALICE-USD',
        'AMP-USD.csv': 'AMP-USD',
        'ANC-USD.csv': 'ANC-USD',
        'ANKR-USD.csv': 'ANKR-USD',
        'ANML-USD.csv': 'ANML-USD',
        'ANT-USD.csv': 'ANT-USD',
        'ANTEX-USD.csv': 'ANTEX-USD',
        'ANV-USD.csv': 'ANV-USD',
        'APE-USD.csv': 'APE-USD',
        'API3-USD.csv': 'API3-USD',
        'APN-USD.csv': 'APN-USD',
        'APT-USD.csv': 'APT-USD',
        'AQT-USD.csv': 'AQT-USD',
        'AR-USD.csv': 'AR-USD',
        'ARG-USD.csv': 'ARG-USD',
        'ARKN-USD.csv': 'ARKN-USD',
        'ARPA-USD.csv': 'ARPA-USD',
        'ARV-USD.csv': 'ARV-USD',
        'AST-USD.csv': 'AST-USD',
        'ASTR-USD.csv': 'ASTR-USD',
        'ATM-USD.csv': 'ATM-USD',
        'ATOM-USD.csv': 'ATOM-USD',
        'ATP-USD.csv': 'ATP-USD',
        'ATS-USD.csv': 'ATS-USD',
        'AUCTION-USD.csv': 'AUCTION-USD',
        'AUDIO-USD.csv': 'AUDIO-USD',
        'AURORA-USD.csv': 'AURORA-USD',
        'AURY-USD.csv': 'AURY-USD',
        'AVAX-USD.csv': 'AVAX-USD',
        'AXS-USD.csv': 'AXS-USD',
        'AZERO-USD.csv': 'AZERO-USD',
        'BABY-USD.csv': 'BABY-USD',
        'BABYDOGE-USD.csv': 'BABYDOGE-USD',
        'BADGER-USD.csv': 'BADGER-USD',
        'BAGS-USD.csv': 'BAGS-USD',
        'BAL-USD.csv': 'BAL-USD',
        'BAND-USD.csv': 'BAND-USD',
        'BAT-USD.csv': 'BAT-USD',
        'BBC-USD.csv': 'BBC-USD',
        'BBF-USD.csv': 'BBF-USD',
        'BCH-USD.csv': 'BCH-USD',
        'BERRY-USD.csv': 'BERRY-USD',
        'BETH-USD.csv': 'BETH-USD',
        'BHD-USD.csv': 'BHD-USD',
        'BICO-USD.csv': 'BICO-USD',
        'BIT-USD.csv': 'BIT-USD',
        'BITCI-USD.csv': 'BITCI-USD',
        'BIX-USD.csv': 'BIX-USD',
        'BLD-USD.csv': 'BLD-USD',
        'BLUR-USD.csv': 'BLUR-USD',
        'BLZ-USD.csv': 'BLZ-USD',
        'BNB-USD.csv': 'BNB-USD',
        'BNT-USD.csv': 'BNT-USD',
        'BOBA-USD.csv': 'BOBA-USD',
        'BONK-USD.csv': 'BONK-USD',
        'BOO-USD.csv': 'BOO-USD',
        'BORING-USD.csv': 'BORING-USD',
        'BOSON-USD.csv': 'BOSON-USD',
        'BOT-USD.csv': 'BOT-USD',
        'BOX-USD.csv': 'BOX-USD',
        'BP-USD.csv': 'BP-USD',
        'BREED-USD.csv': 'BREED-USD',
        'BRISE-USD.csv': 'BRISE-USD',
        'BRT-USD.csv': 'BRT-USD',
        'BRWL-USD.csv': 'BRWL-USD',
        'BSV-USD.csv': 'BSV-USD',
        'BTC-USD.csv': 'BTC-USD',
        'BTM-USD.csv': 'BTM-USD',
        'BTS-USD.csv': 'BTS-USD',
        'BTT-USD.csv': 'BTT-USD',
        'BULL-USD.csv': 'BULL-USD',
        'BWO-USD.csv': 'BWO-USD',
        'C98-USD.csv': 'C98-USD',
        'CAKE-USD.csv': 'CAKE-USD',
        'CAN-USD.csv': 'CAN-USD',
        'CAW-USD.csv': 'CAW-USD',
        'CEEK-USD.csv': 'CEEK-USD',
        'CEL-USD.csv': 'CEL-USD',
        'CELO-USD.csv': 'CELO-USD',
        'CERE-USD.csv': 'CERE-USD',
        'CHR-USD.csv': 'CHR-USD',
        'CHSB-USD.csv': 'CHSB-USD',
        'CHZ-USD.csv': 'CHZ-USD',
        'CKB-USD.csv': 'CKB-USD',
        'CLV-USD.csv': 'CLV-USD',
        'CMT-USD.csv': 'CMT-USD',
        'CNNS-USD.csv': 'CNNS-USD',
        'COL-USD.csv': 'COL-USD',
        'COMP-USD.csv': 'COMP-USD',
        'CORE-USD.csv': 'CORE-USD',
        'COTI-USD.csv': 'COTI-USD',
        'CRE-USD.csv': 'CRE-USD',
        'CRO-USD.csv': 'CRO-USD',
        'CRPT-USD.csv': 'CRPT-USD',
        'CRTS-USD.csv': 'CRTS-USD',
        'CRU-USD.csv': 'CRU-USD',
        'CRV-USD.csv': 'CRV-USD',
        'CSPR-USD.csv': 'CSPR-USD',
        'CTC-USD.csv': 'CTC-USD',
        'CTSI-USD.csv': 'CTSI-USD',
        'CTX-USD.csv': 'CTX-USD',
        'CTXC-USD.csv': 'CTXC-USD',
        'CUBE-USD.csv': 'CUBE-USD',
        'CUDOS-USD.csv': 'CUDOS-USD',
        'CUSD-USD.csv': 'CUSD-USD',
        'CVC-USD.csv': 'CVC-USD',
        'CVP-USD.csv': 'CVP-USD',
        'CVX-USD.csv': 'CVX-USD',
        'DAC-USD.csv': 'DAC-USD',
        'DAI-USD.csv': 'DAI-USD',
        'DAO-USD.csv': 'DAO-USD',
        'DASH-USD.csv': 'DASH-USD',
        'DBC-USD.csv': 'DBC-USD',
        'DC-USD.csv': 'DC-USD',
        'DCR-USD.csv': 'DCR-USD',
        'DEP-USD.csv': 'DEP-USD',
        'DEXE-USD.csv': 'DEXE-USD',
        'DF-USD.csv': 'DF-USD',
        'DFA-USD.csv': 'DFA-USD',
        'DFI-USD.csv': 'DFI-USD',
        'DFX-USD.csv': 'DFX-USD',
        'DHT-USD.csv': 'DHT-USD',
        'DIA-USD.csv': 'DIA-USD',
        'DIE-USD.csv': 'DIE-USD',
        'DIO-USD.csv': 'DIO-USD',
        'DKA-USD.csv': 'DKA-USD',
        'DKS-USD.csv': 'DKS-USD',
        'DOCK-USD.csv': 'DOCK-USD',
        'DODO-USD.csv': 'DODO-USD',
        'DOG-USD.csv': 'DOG-USD',
        'DOGE-USD.csv': 'DOGE-USD',
        'DORA-USD.csv': 'DORA-USD',
        'DOSE-USD.csv': 'DOSE-USD',
        'DOT-USD.csv': 'DOT-USD',
        'DTA-USD.csv': 'DTA-USD',
        'DUSK-USD.csv': 'DUSK-USD',
        'DYDX-USD.csv': 'DYDX-USD',
        'DYP-USD.csv': 'DYP-USD',
        'DZOO-USD.csv': 'DZOO-USD',
        'EDEN-USD.csv': 'EDEN-USD',
        'EFI-USD.csv': 'EFI-USD',
        'EGAME-USD.csv': 'EGAME-USD',
        'EGLD-USD.csv': 'EGLD-USD',
        'EGS-USD.csv': 'EGS-USD',
        'EGT-USD.csv': 'EGT-USD',
        'EKT-USD.csv': 'EKT-USD',
        'ELA-USD.csv': 'ELA-USD',
        'ELF-USD.csv': 'ELF-USD',
        'ELON-USD.csv': 'ELON-USD',
        'ELU-USD.csv': 'ELU-USD',
        'EM-USD.csv': 'EM-USD',
        'ENJ-USD.csv': 'ENJ-USD',
        'ENS-USD.csv': 'ENS-USD',
        'EOS-USD.csv': 'EOS-USD',
        'EPIK-USD.csv': 'EPIK-USD',
        'ERG-USD.csv': 'ERG-USD',
        'ERN-USD.csv': 'ERN-USD',
        'ERTHA-USD.csv': 'ERTHA-USD',
        'ETC-USD.csv': 'ETC-USD',
        'ETH-USD.csv': 'ETH-USD',
        'ETHF-USD.csv': 'ETHF-USD',
        'ETHW-USD.csv': 'ETHW-USD',
        'EUL-USD.csv': 'EUL-USD',
        'EURT-USD.csv': 'EURT-USD',
        'EVER-USD.csv': 'EVER-USD',
        'EVMOS-USD.csv': 'EVMOS-USD',
        'FACE-USD.csv': 'FACE-USD',
        'FANC-USD.csv': 'FANC-USD',
        'FDT-USD.csv': 'FDT-USD',
        'FET-USD.csv': 'FET-USD',
        'FIL-USD.csv': 'FIL-USD',
        'FILDA-USD.csv': 'FILDA-USD',
        'FIO-USD.csv': 'FIO-USD',
        'FIRO-USD.csv': 'FIRO-USD',
        'FIS-USD.csv': 'FIS-USD',
        'FITFI-USD.csv': 'FITFI-USD',
        'FIU-USD.csv': 'FIU-USD',
        'FLOKI-USD.csv': 'FLOKI-USD',
        'FLOW-USD.csv': 'FLOW-USD',
        'FLR-USD.csv': 'FLR-USD',
        'FLZ-USD.csv': 'FLZ-USD',
        'FOR-USD.csv': 'FOR-USD',
        'FORTH-USD.csv': 'FORTH-USD',
        'FOX-USD.csv': 'FOX-USD',
        'FRONT-USD.csv': 'FRONT-USD',
        'FSN-USD.csv': 'FSN-USD',
        'FTI-USD.csv': 'FTI-USD',
        'FTM-USD.csv': 'FTM-USD',
        'FTT-USD.csv': 'FTT-USD',
        'FUD-USD.csv': 'FUD-USD',
        'FUSE-USD.csv': 'FUSE-USD',
        'FX-USD.csv': 'FX-USD',
        'GAL-USD.csv': 'GAL-USD',
        'GALA-USD.csv': 'GALA-USD',
        'GARI-USD.csv': 'GARI-USD',
        'GCOIN-USD.csv': 'GCOIN-USD',
        'GEAR-USD.csv': 'GEAR-USD',
        'GF-USD.csv': 'GF-USD',
        'GFT-USD.csv': 'GFT-USD',
        'GHST-USD.csv': 'GHST-USD',
        'GLM-USD.csv': 'GLM-USD',
        'GLMR-USD.csv': 'GLMR-USD',
        'GMEE-USD.csv': 'GMEE-USD',
        'GMPD-USD.csv': 'GMPD-USD',
        'GMT-USD.csv': 'GMT-USD',
        'GMX-USD.csv': 'GMX-USD',
        'GNO-USD.csv': 'GNO-USD',
        'GNX-USD.csv': 'GNX-USD',
        'GODS-USD.csv': 'GODS-USD',
        'GOF-USD.csv': 'GOF-USD',
        'GPT-USD.csv': 'GPT-USD',
        'GQ-USD.csv': 'GQ-USD',
        'GRAIL-USD.csv': 'GRAIL-USD',
        'GRT-USD.csv': 'GRT-USD',
        'GRV-USD.csv': 'GRV-USD',
        'GST-USD.csv': 'GST-USD',
        'GT-USD.csv': 'GT-USD',
        'GVR-USD.csv': 'GVR-USD',
        'GXC-USD.csv': 'GXC-USD',
        'H2O-USD.csv': 'H2O-USD',
        'HAO-USD.csv': 'HAO-USD',
        'HBAR-USD.csv': 'HBAR-USD',
        'HBB-USD.csv': 'HBB-USD',
        'HBC-USD.csv': 'HBC-USD',
        'HC-USD.csv': 'HC-USD',
        'HEC-USD.csv': 'HEC-USD',
        'HFT-USD.csv': 'HFT-USD',
        'HIT-USD.csv': 'HIT-USD',
        'HIVE-USD.csv': 'HIVE-USD',
        'HOOP-USD.csv': 'HOOP-USD',
        'HOT-USD.csv': 'HOT-USD',
        'HOTCROSS-USD.csv': 'HOTCROSS-USD',
        'HPT-USD.csv': 'HPT-USD',
        'HSF-USD.csv': 'HSF-USD',
        'HT-USD.csv': 'HT-USD',
        'HTR-USD.csv': 'HTR-USD',
        'HUNT-USD.csv': 'HUNT-USD',
        'HYPE-USD.csv': 'HYPE-USD',
        'ICP-USD.csv': 'ICP-USD',
        'ICX-USD.csv': 'ICX-USD',
        'IDEX-USD.csv': 'IDEX-USD',
        'IGU-USD.csv': 'IGU-USD',
        'IMX-USD.csv': 'IMX-USD',
        'INDI-USD.csv': 'INDI-USD',
        'ING-USD.csv': 'ING-USD',
        'INJ-USD.csv': 'INJ-USD',
        'INR-USD.csv': 'INR-USD',
        'INSUR-USD.csv': 'INSUR-USD',
        'INV-USD.csv': 'INV-USD',
        'IOI-USD.csv': 'IOI-USD',
        'IOST-USD.csv': 'IOST-USD',
        'IOTX-USD.csv': 'IOTX-USD',
        'IPV-USD.csv': 'IPV-USD',
        'IRIS-USD.csv': 'IRIS-USD',
        'ITA-USD.csv': 'ITA-USD',
        'ITC-USD.csv': 'ITC-USD',
        'JASMY-USD.csv': 'JASMY-USD',
        'JOY-USD.csv': 'JOY-USD',
        'JST-USD.csv': 'JST-USD',
        'JUMBO-USD.csv': 'JUMBO-USD',
        'JUV-USD.csv': 'JUV-USD',
        'KAI-USD.csv': 'KAI-USD',
        'KAN-USD.csv': 'KAN-USD',
        'KAVA-USD.csv': 'KAVA-USD',
        'KCAL-USD.csv': 'KCAL-USD',
        'KCASH-USD.csv': 'KCASH-USD',
        'KCT-USD.csv': 'KCT-USD',
        'KICKS-USD.csv': 'KICKS-USD',
        'KLAY-USD.csv': 'KLAY-USD',
        'KLV-USD.csv': 'KLV-USD',
        'KMA-USD.csv': 'KMA-USD',
        'KNC-USD.csv': 'KNC-USD',
        'KOI-USD.csv': 'KOI-USD',
        'KOK-USD.csv': 'KOK-USD',
        'KRIPTO-USD.csv': 'KRIPTO-USD',
        'KRRX-USD.csv': 'KRRX-USD',
        'KSM-USD.csv': 'KSM-USD',
        'KT-USD.csv': 'KT-USD',
        'KUBE-USD.csv': 'KUBE-USD',
        'LAMB-USD.csv': 'LAMB-USD',
        'LAT-USD.csv': 'LAT-USD',
        'LBA-USD.csv': 'LBA-USD',
        'LBL-USD.csv': 'LBL-USD',
        'LBP-USD.csv': 'LBP-USD',
        'LDO-USD.csv': 'LDO-USD',
        'LET-USD.csv': 'LET-USD',
        'LHB-USD.csv': 'LHB-USD',
        'LIKE-USD.csv': 'LIKE-USD',
        'LINA-USD.csv': 'LINA-USD',
        'LINK-USD.csv': 'LINK-USD',
        'LITH-USD.csv': 'LITH-USD',
        'LMR-USD.csv': 'LMR-USD',
        'LN-USD.csv': 'LN-USD',
        'LOKA-USD.csv': 'LOKA-USD',
        'LOL-USD.csv': 'LOL-USD',
        'LOOKS-USD.csv': 'LOOKS-USD',
        'LOOM-USD.csv': 'LOOM-USD',
        'LOOT-USD.csv': 'LOOT-USD',
        'LOVE-USD.csv': 'LOVE-USD',
        'LOVELY-USD.csv': 'LOVELY-USD',
        'LPT-USD.csv': 'LPT-USD',
        'LQTY-USD.csv': 'LQTY-USD',
        'LRC-USD.csv': 'LRC-USD',
        'LTC-USD.csv': 'LTC-USD',
        'LUNA-USD.csv': 'LUNA-USD',
        'LUNC-USD.csv': 'LUNC-USD',
        'LUNR-USD.csv': 'LUNR-USD',
        'LXT-USD.csv': 'LXT-USD',
        'MAGIC-USD.csv': 'MAGIC-USD',
        'MANA-USD.csv': 'MANA-USD',
        'MASK-USD.csv': 'MASK-USD',
        'MASS-USD.csv': 'MASS-USD',
        'MATCH-USD.csv': 'MATCH-USD',
        'MATIC-USD.csv': 'MATIC-USD',
        'MBL-USD.csv': 'MBL-USD',
        'MBOX-USD.csv': 'MBOX-USD',
        'MBX-USD.csv': 'MBX-USD',
        'MC-USD.csv': 'MC-USD',
        'MCG-USD.csv': 'MCG-USD',
        'MCO-USD.csv': 'MCO-USD',
        'MCONTENT-USD.csv': 'MCONTENT-USD',
        'MCRT-USD.csv': 'MCRT-USD',
        'MDS-USD.csv': 'MDS-USD',
        'MDX-USD.csv': 'MDX-USD',
        'MESA-USD.csv': 'MESA-USD',
        'METIS-USD.csv': 'METIS-USD',
        'MEV-USD.csv': 'MEV-USD',
        'MGG-USD.csv': 'MGG-USD',
        'MINA-USD.csv': 'MINA-USD',
        'MINE-USD.csv': 'MINE-USD',
        'MIR-USD.csv': 'MIR-USD',
        'MKR-USD.csv': 'MKR-USD',
        'MLK-USD.csv': 'MLK-USD',
        'MLN-USD.csv': 'MLN-USD',
        'MMF-USD.csv': 'MMF-USD',
        'MONO-USD.csv': 'MONO-USD',
        'MOOV-USD.csv': 'MOOV-USD',
        'MOVEZ-USD.csv': 'MOVEZ-USD',
        'MOVR-USD.csv': 'MOVR-USD',
        'MPL-USD.csv': 'MPL-USD',
        'MPLX-USD.csv': 'MPLX-USD',
        'MRS-USD.csv': 'MRS-USD',
        'MTA-USD.csv': 'MTA-USD',
        'MTL-USD.csv': 'MTL-USD',
        'MU-USD.csv': 'MU-USD',
        'MUDOL2-USD.csv': 'MUDOL2-USD',
        'MULTI-USD.csv': 'MULTI-USD',
        'MX-USD.csv': 'MX-USD',
        'MXC-USD.csv': 'MXC-USD',
        'NANO-USD.csv': 'NANO-USD',
        'NAS-USD.csv': 'NAS-USD',
        'NBS-USD.csv': 'NBS-USD',
        'NCASH-USD.csv': 'NCASH-USD',
        'NCT-USD.csv': 'NCT-USD',
        'NEAR-USD.csv': 'NEAR-USD',
        'NEO-USD.csv': 'NEO-USD',
        'NEST-USD.csv': 'NEST-USD',
        'NEW-USD.csv': 'NEW-USD',
        'NEXO-USD.csv': 'NEXO-USD',
        'NFT-USD.csv': 'NFT-USD',
        'NGL-USD.csv': 'NGL-USD',
        'NKN-USD.csv': 'NKN-USD',
        'NODE-USD.csv': 'NODE-USD',
        'NODL-USD.csv': 'NODL-USD',
        'NOIA-USD.csv': 'NOIA-USD',
        'NPT-USD.csv': 'NPT-USD',
        'NSURE-USD.csv': 'NSURE-USD',
        'NT-USD.csv': 'NT-USD',
        'NU-USD.csv': 'NU-USD',
        'NULS-USD.csv': 'NULS-USD',
        'NUM-USD.csv': 'NUM-USD',
        'NYM-USD.csv': 'NYM-USD',
        'O3-USD.csv': 'O3-USD',
        'OAS-USD.csv': 'OAS-USD',
        'OCEAN-USD.csv': 'OCEAN-USD',
        'OCN-USD.csv': 'OCN-USD',
        'OCT-USD.csv': 'OCT-USD',
        'OG-USD.csv': 'OG-USD',
        'OGN-USD.csv': 'OGN-USD',
        'OGO-USD.csv': 'OGO-USD',
        'OGV-USD.csv': 'OGV-USD',
        'OLAND-USD.csv': 'OLAND-USD',
        'OMG-USD.csv': 'OMG-USD',
        'ONE-USD.csv': 'ONE-USD',
        'ONIT-USD.csv': 'ONIT-USD',
        'ONSTON-USD.csv': 'ONSTON-USD',
        'ONT-USD.csv': 'ONT-USD',
        'OP-USD.csv': 'OP-USD',
        'OPUL-USD.csv': 'OPUL-USD',
        'ORB-USD.csv': 'ORB-USD',
        'ORBR-USD.csv': 'ORBR-USD',
        'ORBS-USD.csv': 'ORBS-USD',
        'ORC-USD.csv': 'ORC-USD',
        'OXT-USD.csv': 'OXT-USD',
        'PAI-USD.csv': 'PAI-USD',
        'PANDO-USD.csv': 'PANDO-USD',
        'PARADOX-USD.csv': 'PARADOX-USD',
        'PBR-USD.csv': 'PBR-USD',
        'PEARL-USD.csv': 'PEARL-USD',
        'PEOPLE-USD.csv': 'PEOPLE-USD',
        'PERP-USD.csv': 'PERP-USD',
        'PGALA-USD.csv': 'PGALA-USD',
        'PHA-USD.csv': 'PHA-USD',
        'PHB-USD.csv': 'PHB-USD',
        'PHCR-USD.csv': 'PHCR-USD',
        'PI-USD.csv': 'PI-USD',
        'PLA-USD.csv': 'PLA-USD',
        'PLATO-USD.csv': 'PLATO-USD',
        'PLU-USD.csv': 'PLU-USD',
        'PLY-USD.csv': 'PLY-USD',
        'POKT-USD.csv': 'POKT-USD',
        'POLC-USD.csv': 'POLC-USD',
        'POLS-USD.csv': 'POLS-USD',
        'POLYX-USD.csv': 'POLYX-USD',
        'POND-USD.csv': 'POND-USD',
        'POOLZ-USD.csv': 'POOLZ-USD',
        'POR-USD.csv': 'POR-USD',
        'PRIMATE-USD.csv': 'PRIMATE-USD',
        'PROM-USD.csv': 'PROM-USD',
        'PRQ-USD.csv': 'PRQ-USD',
        'PSG-USD.csv': 'PSG-USD',
        'PSTAKE-USD.csv': 'PSTAKE-USD',
        'PUNDIX-USD.csv': 'PUNDIX-USD',
        'PUSH-USD.csv': 'PUSH-USD',
        'PVT-USD.csv': 'PVT-USD',
        'PYR-USD.csv': 'PYR-USD',
        'QOM-USD.csv': 'QOM-USD',
        'QRDO-USD.csv': 'QRDO-USD',
        'QTUM-USD.csv': 'QTUM-USD',
        'RAB-USD.csv': 'RAB-USD',
        'RACA-USD.csv': 'RACA-USD',
        'RAD-USD.csv': 'RAD-USD',
        'RADAR-USD.csv': 'RADAR-USD',
        'RAIN-USD.csv': 'RAIN-USD',
        'RANKER-USD.csv': 'RANKER-USD',
        'RCCC-USD.csv': 'RCCC-USD',
        'RDNT-USD.csv': 'RDNT-USD',
        'REEF-USD.csv': 'REEF-USD',
        'REI-USD.csv': 'REI-USD',
        'REN-USD.csv': 'REN-USD',
        'REQ-USD.csv': 'REQ-USD',
        'RETH-USD.csv': 'RETH-USD',
        'REVO-USD.csv': 'REVO-USD',
        'REVV-USD.csv': 'REVV-USD',
        'RIFI-USD.csv': 'RIFI-USD',
        'RING-USD.csv': 'RING-USD',
        'RLC-USD.csv': 'RLC-USD',
        'RLY-USD.csv': 'RLY-USD',
        'RNDR-USD.csv': 'RNDR-USD',
        'ROCO-USD.csv': 'ROCO-USD',
        'ROUTE-USD.csv': 'ROUTE-USD',
        'RPL-USD.csv': 'RPL-USD',
        'RSR-USD.csv': 'RSR-USD',
        'RSS3-USD.csv': 'RSS3-USD',
        'RUFF-USD.csv': 'RUFF-USD',
        'RVN-USD.csv': 'RVN-USD',
        'RYOMA-USD.csv': 'RYOMA-USD',
        'SAND-USD.csv': 'SAND-USD',
        'SAO-USD.csv': 'SAO-USD',
        'SC-USD.csv': 'SC-USD',
        'SCREAM-USD.csv': 'SCREAM-USD',
        'SCRT-USD.csv': 'SCRT-USD',
        'SD-USD.csv': 'SD-USD',
        'SDAO-USD.csv': 'SDAO-USD',
        'SDN-USD.csv': 'SDN-USD',
        'SEAN-USD.csv': 'SEAN-USD',
        'SEELE-USD.csv': 'SEELE-USD',
        'SFUND-USD.csv': 'SFUND-USD',
        'SHIB-USD.csv': 'SHIB-USD',
        'SHIT-USD.csv': 'SHIT-USD',
        'SIGN-USD.csv': 'SIGN-USD',
        'SIS-USD.csv': 'SIS-USD',
        'SKEB-USD.csv': 'SKEB-USD',
        'SKL-USD.csv': 'SKL-USD',
        'SKM-USD.csv': 'SKM-USD',
        'SKU-USD.csv': 'SKU-USD',
        'SLC-USD.csv': 'SLC-USD',
        'SMCW-USD.csv': 'SMCW-USD',
        'SMT-USD.csv': 'SMT-USD',
        'SNS-USD.csv': 'SNS-USD',
        'SNT-USD.csv': 'SNT-USD',
        'SNX-USD.csv': 'SNX-USD',
        'SOC-USD.csv': 'SOC-USD',
        'SOFI-USD.csv': 'SOFI-USD',
        'SOL-USD.csv': 'SOL-USD',
        'SOLO-USD.csv': 'SOLO-USD',
        'SOS-USD.csv': 'SOS-USD',
        'SOUL-USD.csv': 'SOUL-USD',
        'SPA-USD.csv': 'SPA-USD',
        'SPELL-USD.csv': 'SPELL-USD',
        'SPELLFIRE-USD.csv': 'SPELLFIRE-USD',
        'SPRT-USD.csv': 'SPRT-USD',
        'SPS-USD.csv': 'SPS-USD',
        'SPUME-USD.csv': 'SPUME-USD',
        'SRM-USD.csv': 'SRM-USD',
        'SRT-USD.csv': 'SRT-USD',
        'SSV-USD.csv': 'SSV-USD',
        'STAKE-USD.csv': 'STAKE-USD',
        'STARLY-USD.csv': 'STARLY-USD',
        'STC-USD.csv': 'STC-USD',
        'STEEM-USD.csv': 'STEEM-USD',
        'STETH-USD.csv': 'STETH-USD',
        'STF-USD.csv': 'STF-USD',
        'STG-USD.csv': 'STG-USD',
        'STN-USD.csv': 'STN-USD',
        'STORE-USD.csv': 'STORE-USD',
        'STORJ-USD.csv': 'STORJ-USD',
        'STPT-USD.csv': 'STPT-USD',
        'STRM-USD.csv': 'STRM-USD',
        'SUDO-USD.csv': 'SUDO-USD',
        'SUKU-USD.csv': 'SUKU-USD',
        'SUN-USD.csv': 'SUN-USD',
        'SUPER-USD.csv': 'SUPER-USD',
        'SUSHI-USD.csv': 'SUSHI-USD',
        'SWAP-USD.csv': 'SWAP-USD',
        'SWEAT-USD.csv': 'SWEAT-USD',
        'SWFTC-USD.csv': 'SWFTC-USD',
        'SWRV-USD.csv': 'SWRV-USD',
        'SXP-USD.csv': 'SXP-USD',
        'SYLO-USD.csv': 'SYLO-USD',
        'SYN-USD.csv': 'SYN-USD',
        'SYS-USD.csv': 'SYS-USD',
        'T-USD.csv': 'T-USD',
        'TALK-USD.csv': 'TALK-USD',
        'TAO-USD.csv': 'TAO-USD',
        'TAVA-USD.csv': 'TAVA-USD',
        'TCNH-USD.csv': 'TCNH-USD',
        'TDX-USD.csv': 'TDX-USD',
        'THETA-USD.csv': 'THETA-USD',
        'TINC-USD.csv': 'TINC-USD',
        'TITAN-USD.csv': 'TITAN-USD',
        'TLM-USD.csv': 'TLM-USD',
        'TLOS-USD.csv': 'TLOS-USD',
        'TNB-USD.csv': 'TNB-USD',
        'TOKE-USD.csv': 'TOKE-USD',
        'TOMI-USD.csv': 'TOMI-USD',
        'TOMS-USD.csv': 'TOMS-USD',
        'TON-USD.csv': 'TON-USD',
        'TOP-USD.csv': 'TOP-USD',
        'TORN-USD.csv': 'TORN-USD',
        'TRAC-USD.csv': 'TRAC-USD',
        'TRACE-USD.csv': 'TRACE-USD',
        'TRB-USD.csv': 'TRB-USD',
        'TRIBE-USD.csv': 'TRIBE-USD',
        'TRU-USD.csv': 'TRU-USD',
        'TRX-USD.csv': 'TRX-USD',
        'TT-USD.csv': 'TT-USD',
        'TUSD-USD.csv': 'TUSD-USD',
        'UFT-USD.csv': 'UFT-USD',
        'UIP-USD.csv': 'UIP-USD',
        'UMA-USD.csv': 'UMA-USD',
        'UNB-USD.csv': 'UNB-USD',
        'UNFI-USD.csv': 'UNFI-USD',
        'UNI-USD.csv': 'UNI-USD',
        'UNIC-USD.csv': 'UNIC-USD',
        'UNQ-USD.csv': 'UNQ-USD',
        'UOS-USD.csv': 'UOS-USD',
        'UPI-USD.csv': 'UPI-USD',
        'USDC-USD.csv': 'USDC-USD',
        'USDD-USD.csv': 'USDD-USD',
        'USDJ-USD.csv': 'USDJ-USD',
        'USDP-USD.csv': 'USDP-USD',
        'USN-USD.csv': 'USN-USD',
        'USTC-USD.csv': 'USTC-USD',
        'UTK-USD.csv': 'UTK-USD',
        'UUU-USD.csv': 'UUU-USD',
        'VALUE-USD.csv': 'VALUE-USD',
        'VELO-USD.csv': 'VELO-USD',
        'VEMP-USD.csv': 'VEMP-USD',
        'VEN-USD.csv': 'VEN-USD',
        'VET-USD.csv': 'VET-USD',
        'VIDY-USD.csv': 'VIDY-USD',
        'VINU-USD.csv': 'VINU-USD',
        'VISION-USD.csv': 'VISION-USD',
        'VLX-USD.csv': 'VLX-USD',
        'VOLT-USD.csv': 'VOLT-USD',
        'VOXEL-USD.csv': 'VOXEL-USD',
        'VPAD-USD.csv': 'VPAD-USD',
        'VR-USD.csv': 'VR-USD',
        'VRA-USD.csv': 'VRA-USD',
        'VSYS-USD.csv': 'VSYS-USD',
        'VVS-USD.csv': 'VVS-USD',
        'WALLET-USD.csv': 'WALLET-USD',
        'WAR-USD.csv': 'WAR-USD',
        'WAVES-USD.csv': 'WAVES-USD',
        'WAXP-USD.csv': 'WAXP-USD',
        'WBT-USD.csv': 'WBT-USD',
        'WBTC-USD.csv': 'WBTC-USD',
        'WE-USD.csv': 'WE-USD',
        'WELL-USD.csv': 'WELL-USD',
        'WEMIX-USD.csv': 'WEMIX-USD',
        'WHALE-USD.csv': 'WHALE-USD',
        'WICC-USD.csv': 'WICC-USD',
        'WILD-USD.csv': 'WILD-USD',
        'WIN-USD.csv': 'WIN-USD',
        'WLKN-USD.csv': 'WLKN-USD',
        'WMT-USD.csv': 'WMT-USD',
        'WND-USD.csv': 'WND-USD',
        'WNDR-USD.csv': 'WNDR-USD',
        'WNXM-USD.csv': 'WNXM-USD',
        'WOO-USD.csv': 'WOO-USD',
        'WOOF-USD.csv': 'WOOF-USD',
        'WOZX-USD.csv': 'WOZX-USD',
        'WTC-USD.csv': 'WTC-USD',
        'WWY-USD.csv': 'WWY-USD',
        'WXT-USD.csv': 'WXT-USD',
        'XAUT-USD.csv': 'XAUT-USD',
        'XCAD-USD.csv': 'XCAD-USD',
        'XCH-USD.csv': 'XCH-USD',
        'XCN-USD.csv': 'XCN-USD',
        'XCUR-USD.csv': 'XCUR-USD',
        'XDC-USD.csv': 'XDC-USD',
        'XDEFI-USD.csv': 'XDEFI-USD',
        'XEC-USD.csv': 'XEC-USD',
        'XEM-USD.csv': 'XEM-USD',
        'XEN-USD.csv': 'XEN-USD',
        'XETA-USD.csv': 'XETA-USD',
        'XLM-USD.csv': 'XLM-USD',
        'XMR-USD.csv': 'XMR-USD',
        'XMX-USD.csv': 'XMX-USD',
        'XNO-USD.csv': 'XNO-USD',
        'XPLA-USD.csv': 'XPLA-USD',
        'XPRT-USD.csv': 'XPRT-USD',
        'XRP-USD.csv': 'XRP-USD',
        'XRT-USD.csv': 'XRT-USD',
        'XTM-USD.csv': 'XTM-USD',
        'XTZ-USD.csv': 'XTZ-USD',
        'XVG-USD.csv': 'XVG-USD',
        'XYO-USD.csv': 'XYO-USD',
        'YAM-USD.csv': 'YAM-USD',
        'YAMV2-USD.csv': 'YAMV2-USD',
        'YEE-USD.csv': 'YEE-USD',
        'YFI-USD.csv': 'YFI-USD',
        'YFII-USD.csv': 'YFII-USD',
        'YGG-USD.csv': 'YGG-USD',
        'ZBC-USD.csv': 'ZBC-USD',
        'ZCX-USD.csv': 'ZCX-USD',
        'ZEC-USD.csv': 'ZEC-USD',
        'ZED-USD.csv': 'ZED-USD',
        'ZEN-USD.csv': 'ZEN-USD',
        'ZIG-USD.csv': 'ZIG-USD',
        'ZIL-USD.csv': 'ZIL-USD',
        'ZKP-USD.csv': 'ZKP-USD',
        'ZKS-USD.csv': 'ZKS-USD',
        'ZNT-USD.csv': 'ZNT-USD',
        'ZRX-USD.csv': 'ZRX-USD',
    }

    # metas = {"5148.KL.csv": "5148.KL",
    #          "1368.KL.csv": "1368.KL",
    #         }

    # test_cases = metas.keys()
    # test_cases = ['data/S35.SI.csv', 'data/NEAR-USD.csv']
    test_cases = ['btcusdt_backtest.csv']

    scanning_df = pd.DataFrame([], columns=['Name', 'best_score', 'upper_sample', 'lower_sample', 'ATR_sample', 'atr_loss_margin', 'bayes_windows', 'max_invest'])
    for tname in test_cases:
        print(tname)
        try:
            # optimize_func_wrapper = functools.partial(optimize_func, csv_path=f'/Users/zen/Documents/code/FinRPG/data/history_price/{tname}')
            optimize_func_wrapper = functools.partial(optimize_func, csv_path=f'data/{tname}')

            if run_optimize:
            # 定義參數空間
                params = {
                    'upper_sample': (2, 2000),
                    'lower_sample': (2, 2000),
                    'ATR_sample': (2, 2000),
                    'atr_loss_margin': (1, 5),
                    'bayes_windows': (30, 2000),
                    # 'max_invest': (100, 1500),
                }

                optimizer = BayesianOptimization(f=optimize_func_wrapper, pbounds=params, random_state=1)
                optimizer.maximize(init_points=5, n_iter=100)
                best_params = optimizer.max['params']
                best_score = optimizer.max['target']
                import pprint
                print(f'    best_params = {pprint.pformat(best_params)}')
                print('best_score = ', best_score)
                best_params['Name'] = tname
                best_params['best_score'] = best_score
                scanning_df = scanning_df.append(pd.Series(best_params), ignore_index=True)
            # print('--' * 100)
            best_params['debug'] = True
            optimize_func_wrapper(**best_params)
        except Exception as e:
            print(e)
    print(scanning_df)
    scanning_df.to_csv(f'reports/scanning_{len(test_cases)}.csv', index=False)
    print(f'created: scanning_{len(test_cases)}.csv')


def portfolio():
    run_optimize = 0
    #
    best_params_df = pd.read_csv('reports/watching_list.csv')
    best_params_df = best_params_df.sort_values(by=['best_score'])


    metas = { name: name.replace('.csv', '') for name in best_params_df['Name'].values}
    test_cases = metas.keys()
    scanning_df = pd.DataFrame([], columns=['Name', 'best_score', 'upper_sample', 'lower_sample', 'ATR_sample', 'atr_loss_margin', 'bayes_windows', 'max_invest'])
    for tname in test_cases:
        # try:
            best_params = best_params_df[best_params_df.Name == tname].to_dict('records')[0]
            optimize_func_wrapper = functools.partial(optimize_func, csv_path=f'data/{tname}')
            print('--' * 100)
            best_params['debug'] = True
            optimize_func_wrapper(**best_params)
        # except Exception as e:
        #     print(e)
    print(scanning_df)
    # scanning_df.to_csv(f'scanning_{len(test_cases)}.csv', index=False)
    # print(f'created: scanning_{len(test_cases)}.csv')


if __name__ == '__main__':
    pd.set_option('display.max_columns', None)
    pd.set_option('display.float_format', lambda x: '%.5f' % x)
    pd.set_option('display.width', 300)
    run()
    # portfolio()
