import sys, os
import click
import pandas as pd
import matplotlib.pyplot as plt
import mplfinance as mpf
import numpy as np
from dotenv import load_dotenv
from collections import Counter

import seaborn as sns
from quanthunt.story import start_journey
from quanthunt.hunterverse.storage import HuntingCamp
from quanthunt.strategy.turtle_trading import (
    TurtleScout,
    buy_signal_from_mosaic_strategy,
)

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent / "src"))
from huobi.client.market import MarketClient
from huobi.client.generic import GenericClient
from huobi.utils import *
from huobi.constant import *
from quanthunt.utils import pandas_util
from quanthunt.hunterverse.interface import Symbol, DUMP_COL
from config import config
from quanthunt.sensor.market_sensor import (
    HuobiMarketSensor,
    YahooMarketSensor,
    LocalMarketSensor,
)
from quanthunt.strategy.turtle_trading import (
    TurtleScout,
    buy_signal_from_mosaic_strategy,
)
from quanthunt.hunterverse.interface import StrategyParam

DATA_DIR, SRC_DIR, REPORTS_DIR = config.data_dir, config.src_dir, config.reports_dir

# Load API credentials from .env file
load_dotenv(dotenv_path=Path(__file__).resolve().parent / ".env")
api_key = os.getenv("API_KEY")
secret_key = os.getenv("SECRET_KEY")

# from .story import entry
# params = {
#     "ATR_sample": 60,
#     "bayes_windows": 20,
#     "lower_sample": 60,
#     "upper_sample": 60,
#     "hard_cutoff": 0.975,
#     "profit_loss_ratio": 3.0,
#     "atr_loss_margin": 1.0,
#     "surfing_level": 5,
#     "interval": "5min",
#     "funds": 15,
#     "stake_cap": 15,
#     "symbol": Symbol("btcusdt"),
#     "hmm_split": 4,
#     "backtest": False,
#     "debug_mode": [
#         "statement",
#         "statement_to_csv",
#         "mission_review",
#         "final_statement_to_csv",
#     ],
#     "load_deals": [],
#     "start_deal": "",
#     "api_key": None,
#     "secret_key": None,
# }

stocks_singapore = {
    "VNM.SI": "",
    "GRU.SI": "",
    "LCS.SI": "",
    "SQU.SI": "",
    "SHD.SI": "",
    "YLU.SI": "",
    "TATD.SI": "",
    "S45U.SI": "",
    "SSS.SI": "",
    "CXS.SI": "",
    "ICU.SI": "",
    "YLD.SI": "",
    "ICM.SI": "",
    "ESG.SI": "",
    "JJJ.SI": "",
    "VND.SI": "",
    "MCN.SI": "",
    "TCPD.SI": "",
    "LSS.SI": "",
    "GRO.SI": "",
    "LCU.SI": "",
    "SCY.SI": "",
    "TPED.SI": "",
    "SQQ.SI": "",
    "YWTR.SI": "",
    "W4VR.SI": "",
    "AYV.SI": "",
    "Z4D.SI": "",
    "BJD.SI": "",
    "YYB.SI": "",
    "KUH.SI": "",
    "BKK.SI": "",
    "BFK.SI": "",
    "UUK.SI": "",
    "5OR.SI": "",
    "M11.SI": "",
    "LYY.SI": "",
    "M03.SI": "",
    "8A1.SI": "",
    "BEH.SI": "",
    "AWK.SI": "",
    "580.SI": "",
    "1F1.SI": "",
    "1A0.SI": "",
    "9QX.SI": "",
    "584.SI": "",
    "5QR.SI": "",
    "1H3.SI": "",
    "M15.SI": "",
    "40N.SI": "",
    "585.SI": "",
    "5FX.SI": "",
    "5EW.SI": "",
    "1D3.SI": "",
    "QS9.SI": "",
    "5G4.SI": "",
    "5WV.SI": "",
    "8YY.SI": "",
    "5F4.SI": "",
    "41T.SI": "",
    "V2Y.SI": "",
    "49B.SI": "",
    "5TJ.SI": "",
    "1F0.SI": "",
    "V3M.SI": "",
    "5OC.SI": "",
    "GU5.SI": "",
    "AZA.SI": "",
    "KUX.SI": "",
    "42N.SI": "",
    "5DX.SI": "",
    "J03.SI": "",
    "5HH.SI": "",
    "1H2.SI": "",
    "5CR.SI": "",
    "5IF.SI": "",
    "43E.SI": "",
    "BKV.SI": "",
    "BLU.SI": "",
    "532.SI": "",
    "5QY.SI": "",
    "43F.SI": "",
    "504.SI": "",
    "5UA.SI": "",
    "5VP.SI": "",
    "TVV.SI": "",
    "OMK.SI": "",
    "WJ9.SI": "",
    "508.SI": "",
    "570.SI": "",
    "NHD.SI": "",
    "5OQ.SI": "",
    "43A.SI": "",
    "5SY.SI": "",
    "BLZ.SI": "",
    "5EF.SI": "",
    "BCD.SI": "",
    "5PF.SI": "",
    "BAC.SI": "",
    "5EV.SI": "",
    "5G9.SI": "",
    "5NF.SI": "",
    "1L2.SI": "",
    "S3N.SI": "",
    "583.SI": "",
    "SEJ.SI": "",
    "5EB.SI": "",
    "505.SI": "",
    "BTX.SI": "",
    "ENV.SI": "",
    "SES.SI": "",
    "SJY.SI": "",
    "QZG.SI": "",
    "AWG.SI": "",
    "5LE.SI": "",
    "Y06.SI": "",
    "XCF.SI": "",
    "F10.SI": "",
    "N32.SI": "",
    "BAI.SI": "",
    "V8Y.SI": "",
    "41F.SI": "",
    "5AB.SI": "",
    "BJZ.SI": "",
    "5AI.SI": "",
    "CTO.SI": "",
    "A52.SI": "",
    "5BI.SI": "",
    "E6R.SI": "",
    "BDU.SI": "",
    "E27.SI": "",
    "5RA.SI": "",
    "AOF.SI": "",
    "AAJ.SI": "",
    "5KI.SI": "",
    "594.SI": "",
    "R14.SI": "",
    "5AU.SI": "",
    "5EG.SI": "",
    "5AL.SI": "",
    "AWC.SI": "",
    "BJV.SI": "",
    "BQC.SI": "",
    "CIN.SI": "",
    "MF6.SI": "",
    "BNE.SI": "",
    "PRH.SI": "",
    "BAZ.SI": "",
    "FRQ.SI": "",
    "595.SI": "",
    "EHG.SI": "",
    "42F.SI": "",
    "A04.SI": "",
    "RXS.SI": "",
    "BHU.SI": "",
    "NR7.SI": "",
    "42T.SI": "",
    "CHJ.SI": "",
    "G0I.SI": "",
    "1H8.SI": "",
    "1Y1.SI": "",
    "5G2.SI": "",
    "BVQ.SI": "",
    "HQU.SI": "",
    "BTG.SI": "",
    "M05.SI": "",
    "1B0.SI": "",
    "D8DU.SI": "",
    "LS9.SI": "",
    "K29.SI": "",
    "5AE.SI": "",
    "Q0X.SI": "",
    "5HV.SI": "",
    "BLH.SI": "",
    "F86.SI": "",
    "ZB9.SI": "",
    "566.SI": "",
    "42E.SI": "",
    "5SO.SI": "",
    "C9Q.SI": "",
    "S44.SI": "",
    "8K7.SI": "",
    "U77.SI": "",
    "AWI.SI": "",
    "RQ1.SI": "",
    "546.SI": "",
    "C76.SI": "",
    "B69.SI": "",
    "BQD.SI": "",
    "533.SI": "",
    "G50.SI": "",
    "1J5.SI": "",
    "9G2.SI": "",
    "5ML.SI": "",
    "F13.SI": "",
    "S19.SI": "",
    "L02.SI": "",
    "5TP.SI": "",
    "B49.SI": "",
    "40V.SI": "",
    "V7R.SI": "",
    "1F2.SI": "",
    "S23.SI": "",
    "ZKX.SI": "",
    "N08.SI": "",
    "ER0.SI": "",
    "KUO.SI": "",
    "5CF.SI": "",
    "L19.SI": "",
    "564.SI": "",
    "M14.SI": "",
    "BQM.SI": "",
    "WKS.SI": "",
    "1J0.SI": "",
    "L38.SI": "",
    "XJB.SI": "",
    "BCY.SI": "",
    "T12.SI": "",
    "1J4.SI": "",
    "T13.SI": "",
    "1D1.SI": "",
    "BLS.SI": "",
    "BTP.SI": "",
    "5WA.SI": "",
    "I07.SI": "",
    "5WH.SI": "",
    "5VS.SI": "",
    "5IC.SI": "",
    "CLN.SI": "",
    "5DP.SI": "",
    "S7P.SI": "",
    "BPF.SI": "",
    "MR7.SI": "",
    "5WJ.SI": "",
    "41O.SI": "",
    "XZL.SI": "",
    "IX2.SI": "",
    "S7OU.SI": "",
    "OAJ.SI": "",
    "C33.SI": "",
    "BEW.SI": "",
    "A30.SI": "",
    "42R.SI": "",
    "URR.SI": "",
    "D03.SI": "",
    "1MZ.SI": "",
    "QNS.SI": "",
    "5UL.SI": "",
    "A05.SI": "",
    "J2T.SI": "",
    "D5IU.SI": "",
    "U09.SI": "",
    "500.SI": "",
    "DM0.SI": "",
    "5GD.SI": "",
    "MXNU.SI": "",
    "B73.SI": "",
    "JLB.SI": "",
    "BTM.SI": "",
    "5UF.SI": "",
    "DU4.SI": "",
    "TCU.SI": "",
    "579.SI": "",
    "H12.SI": "",
    "5LY.SI": "",
    "BTOU.SI": "",
    "40T.SI": "",
    "LVR.SI": "",
    "5DD.SI": "",
    "Z59.SI": "",
    "F1E.SI": "",
    "S35.SI": "",
    "G20.SI": "",
    "AWZ.SI": "",
    "BN2.SI": "",
    "QC7.SI": "",
    "OXMU.SI": "",
    "5JK.SI": "",
    "BMGU.SI": "",
    "528.SI": "",
    "N02.SI": "",
    "CMOU.SI": "",
    "E3B.SI": "",
    "B58.SI": "",
    "ODBU.SI": "",
    "HLS.SI": "",
    "F83.SI": "",
    "BTE.SI": "",
    "BBW.SI": "",
    "NPW.SI": "",
    "544.SI": "",
    "PPC.SI": "",
    "BDX.SI": "",
    "T24.SI": "",
    "5UX.SI": "",
    "A34.SI": "",
    "Y03.SI": "",
    "P52.SI": "",
    "RE4.SI": "",
    "M01.SI": "",
    "QES.SI": "",
    "B28.SI": "",
    "BHK.SI": "",
    "T6I.SI": "",
    "1D0.SI": "",
    "M1GU.SI": "",
    "S85.SI": "",
    "UD1U.SI": "",
    "MV4.SI": "",
    "AWX.SI": "",
    "U13.SI": "",
    "5JS.SI": "",
    "S56.SI": "",
    "DHLU.SI": "",
    "TSH.SI": "",
    "WJP.SI": "",
    "Q01.SI": "",
    "5IG.SI": "",
    "F9D.SI": "",
    "P34.SI": "",
    "O10.SI": "",
    "C41.SI": "",
    "F03.SI": "",
    "P9D.SI": "",
    "BWM.SI": "",
    "H18.SI": "",
    "MZH.SI": "",
    "5G3.SI": "",
    "E28.SI": "",
    "H07.SI": "",
    "OYY.SI": "",
    "AW9U.SI": "",
    "OU8.SI": "",
    "BEC.SI": "",
    "H22.SI": "",
    "U9E.SI": "",
    "S20.SI": "",
    "CHZ.SI": "",
    "H30.SI": "",
    "NO4.SI": "",
    "UD2.SI": "",
    "G92.SI": "",
    "558.SI": "",
    "S61.SI": "",
    "8AZ.SI": "",
    "Z25.SI": "",
    "DCRU.SI": "",
    "EH5.SI": "",
    "P15.SI": "",
    "CRPU.SI": "",
    "ACV.SI": "",
    "CWBU.SI": "",
    "LJ3.SI": "",
    "5CP.SI": "",
    "B61.SI": "",
    "AGS.SI": "",
    "C70.SI": "",
    "W05.SI": "",
    "S08.SI": "",
    "O5RU.SI": "",
    "S41.SI": "",
    "A26.SI": "",
    "NS8U.SI": "",
    "ADN.SI": "",
    "P40U.SI": "",
    "YF8.SI": "",
    "J85.SI": "",
    "H13.SI": "",
    "P8Z.SI": "",
    "NC2.SI": "",
    "AU8U.SI": "",
    "CWCU.SI": "",
    "A50.SI": "",
    "Q5T.SI": "",
    "AP4.SI": "",
    "U10.SI": "",
    "P7VU.SI": "",
    "JYEU.SI": "",
    "CY6U.SI": "",
    "BSL.SI": "",
    "F17.SI": "",
    "TS0U.SI": "",
    "F99.SI": "",
    "H15.SI": "",
    "M04.SI": "",
    "AIY.SI": "",
    "CC3.SI": "",
    "EB5.SI": "",
    "OV8.SI": "",
    "J91U.SI": "",
    "H02.SI": "",
    "C2PU.SI": "",
    "SK6U.SI": "",
    "D01.SI": "",
    "T14.SI": "",
    "U06.SI": "",
    "T15.SI": "",
    "S59.SI": "",
    "BVA.SI": "",
    "TSCD.SI": "",
    "A7RU.SI": "",
    "C52.SI": "",
    "TQ5.SI": "",
    "E5H.SI": "",
    "CJLU.SI": "",
    "HMN.SI": "",
    "K71U.SI": "",
    "AJBU.SI": "",
    "T82U.SI": "",
    "V03.SI": "",
    "J69U.SI": "",
    "VC2.SI": "",
    "BUOU.SI": "",
    "U14.SI": "",
    "C09.SI": "",
    "S58.SI": "",
    "5E2.SI": "",
    "EMI.SI": "",
    "M44U.SI": "",
    "ME8U.SI": "",
    "N2IU.SI": "",
    "H78.SI": "",
    "U96.SI": "",
    "J36.SI": "",
    "BS6.SI": "",
    "G13.SI": "",
    "C07.SI": "",
    "NIO.SI": "",
    "BN4.SI": "",
    "S68.SI": "",
    "A17U.SI": "",
    "Y92.SI": "",
    "S63.SI": "",
    "TKKD.SI": "",
    "C38U.SI": "",
    "9CI.SI": "",
    "S07.SI": "",
    "Q0F.SI": "",
    "C6L.SI": "",
    "F34.SI": "",
    "K6S.SI": "",
    "TGED.SI": "",
    "TADD.SI": "",
    "TDED.SI": "",
    "U11.SI": "",
    "Z74.SI": "",
    "Z77.SI": "",
    "O39.SI": "",
    "D05.SI": "",
    "UIX.SI": "",
    "43B.SI": "",
    "FQ7.SI": "",
    "554.SI": "",
    "BRD.SI": "",
    "C04.SI": "",
    "541.SI": "",
    "1E3.SI": "",
    "5TT.SI": "",
    "5F7.SI": "",
    "BBP.SI": "",
    "42C.SI": "",
    "AVX.SI": "",
    "41B.SI": "",
    "OTX.SI": "",
    "5GZ.SI": "",
    "BFU.SI": "",
    "B9S.SI": "",
    "BKW.SI": "",
    "5GI.SI": "",
    "K03.SI": "",
    "GRQ.SI": "",
    "1D4.SI": "",
    "1V3.SI": "",
    "5PO.SI": "",
    "OTS.SI": "",
    "A33.SI": "",
    "C06.SI": "",
    "BIX.SI": "",
    "BFI.SI": "",
    "ZXY.SI": "",
    "Y35.SI": "",
    "N01.SI": "",
    "BHD.SI": "",
    "H20.SI": "",
    "5I4.SI": "",
    "CEDU.SI": "",
    "BTJ.SI": "",
    "1A1.SI": "",
    "LMS.SI": "",
    "42W.SI": "",
    "S71.SI": "",
    "1D5.SI": "",
    "AYN.SI": "",
    "BXE.SI": "",
    "CNE.SI": "",
    "5PC.SI": "",
    "Y8E.SI": "",
    "AJ2.SI": "",
    "T41.SI": "",
    "596.SI": "",
    "543.SI": "",
    "BIP.SI": "",
    "540.SI": "",
    "O08.SI": "",
    "P36.SI": "",
    "L23.SI": "",
    "C05.SI": "",
    "P8A.SI": "",
    "B26.SI": "",
    "C13.SI": "",
    "I06.SI": "",
    "BDA.SI": "",
    "5NV.SI": "",
    "A31.SI": "",
    "SGR.SI": "",
    "Y3D.SI": "",
    "TWL.SI": "",
    "KJ5.SI": "",
    "5WF.SI": "",
    "NEX.SI": "",
    "VI2.SI": "",
    "1B1.SI": "",
    "YK9.SI": "",
    "I49.SI": "",
    "BQF.SI": "",
    "T55.SI": "",
    "5G1.SI": "",
    "1R6.SI": "",
    "NLC.SI": "",
    "42L.SI": "",
    "C8R.SI": "",
    "9I7.SI": "",
    "A55.SI": "",
    "S69.SI": "",
    "5MZ.SI": "",
    "O9E.SI": "",
    "5OI.SI": "",
    "BDR.SI": "",
    "1F3.SI": "",
    "BEZ.SI": "",
    "1AZ.SI": "",
    "569.SI": "",
    "S29.SI": "",
    "NXR.SI": "",
    "BKX.SI": "",
    "5DM.SI": "",
    "WPC.SI": "",
    "K75.SI": "",
    "BKA.SI": "",
    # "C6L.SI": "Singapore Airlines - Airline",
    # "U96.SI": "Sembcorp Industries - Utilities",
    # "D05.SI": "DBS Group Holdings - Banking",
    # "Z74.SI": "Singtel - Telecommunications",
    # "C07.SI": "Jardine Cycle & Carriage - Automotive",
    # "BN4.SI": "Keppel Corporation - Conglomerate",
    # "F34.SI": "Wilmar International - Agriculture",
    # "BS6.SI": "Yangzijiang Shipbuilding - Shipbuilding",
    # "O39.SI": "OCBC Bank - Banking",
    # "9CI.SI": "CapitaLand - Real Estate",
    # "U11.SI": "United Overseas Bank - Banking",
    # "N2IU.SI": "Mapletree Commercial Trust - Real Estate",
    # "H78.SI": "Hongkong Land Holdings - Real Estate",
    # "S68.SI": "Singapore Exchange - Financial Services",
    # "A17U.SI": "Ascendas REIT - Real Estate",
    # "C09.SI": "City Developments - Real Estate",
    # "M44U.SI": "Mapletree Logistics Trust - Real Estate",
    # "V03.SI": "Venture Corporation - Electronics",
    # "J69U.SI": "Frasers Logistics & Commercial Trust - Real Estate",
    # "ME8U.SI": "Mapletree Industrial Trust - Real Estate",
    # "AJBU.SI": "Ascott Residence Trust - Hospitality",
    # "NOBGY": "Noble Group - Commodities",
    # "K71U.SI": "Keppel REIT - Real Estate",
    # "G13.SI": "Genting Singapore - Hospitality",
    # "Y92.SI": "Thai Beverage - Beverages",
    # "Q5T.SI": "Far East Hospitallity Trust - REITS",
    # "U14.SI": "UOL Group - Real Estate",
    # "S63.SI": "ST Engineering - Engineering",
    # "NS8U.SI": "Hutchison Port Holdings Trust  - REITS",
    # "C52.SI": "ComfortDelGro - Transportation",
    # "H02.SI": "Haw Par Corporation Limited ",
    # "E5H.SI": "Golden Agri-Resources - Agriculture",
    # "S59.SI": "SIA Engineering - Aerospace",
    # "U09.SI": "Avarga Limited",
    # "O5RU.SI": "AIMS APAC REIT - Real Estate",
    # "BUOU.SI": "Frasers Logistics & Commercial Trust  - Real Estate",
    # "M1GU.SI": "Sabana Industrial Real Estate Investment Trust - Real Estate",
    # "BVA.SI": "Top Glove Corporation Bhd.",
    # "D03.SI": "Del Monte Pacific - Food & Beverage",
    # "P40U.SI": "Starhill Global Real Estate Investment Trust ",
    # "F9D.SI": "Boustead Singapore Limited",
    # "T82U.SI": "Suntec REIT - Real Estate",
    # "TQ5.SI": "Frasers Property - Real Estate",
    # "BSL.SI": "Raffles Medical Group - Healthcare",
    # "1D4.SI": "Aoxin Q & M Dental Group Limited",
    # "NR7.SI": "Raffles Education Corporation - Education",
    # "5CP.SI": "Silverlake Axis - Technology",
    # "T14.SI": "Tianjin Pharmaceutical Da Ren Tang Group Corporation Limited",
    # "C2PU.SI": "Parkway Life Real Estate Investment Trust ",
    # "U96.SI": "Sembcorp Industries - Energy",
    # "5TP.SI": "CNMC Goldmine Holdings Limited",
    # "G07.SI": "Great Eastern - Insurance",
    # "TQ5.SI": "Frasers Property Limited ",
    # "CC3.SI": "StarHub - Telecommunications",
    # "BN4.SI": "Keppel Corporation - Industrial Conglomerate",
    # "C09.SI": "City Developments Limited - Real Estate",
    # "O10.SI": "Far East Orchard - Real Estate",
    # "S58.SI": "SATS Ltd. - Aviation",
    # "Y06.SI": "Green Build Technology Limited",
    # "Z25.SI": "Yanlord Land Group - Real Estate",
    # "Z59.SI": "Yoma Strategic Holdings - Conglomerate",
    # "C76.SI": "Creative Technology - Technology",
    # "A50.SI": "Thomson Medical Group - Healthcare",
    # "5IG.SI": "Gallant Venture Ltd",
    # "1C0.SI": "Emerging Towns & Cities Singapore Ltd.",
    # "C38U.SI": "CapitaLand Integrated Commercial Trust - Real Stack",
    # "C52.SI": "ComfortDelGro Corporation - Transportation",
    # "G92.SI": "China Aviation Oil (Singapore) Corporation Ltd",
    # "CRPU.SI": "Sasseur REIT - Real Estate",
    # "H30.SI": "Hong Fok Corporation Limited",
    # "H13.SI": "Ho Bee Land - Real Estate",
    # "1B1.SI": "HC Surgical Specialists - Healthcare",
    # "AWX.SI": "AEM Holdings Ltd.",
    # "1J5.SI": "Hyphens Pharma - Pharmaceuticals",
    # "B61.SI": "Bukit Sembawang Estates - Real Estate",
    # "A7RU.SI": "Keppel Infrastructure Trust",
    # "BTOU.SI": "Manulife US REIT - Real Estate",
    # "BDA.SI": "PNE Industries Ltd",
    # "9I7.SI": "No Signboard Holdings - Food & Beverage",
    # "BWCU.SI": "EC World Real Estate Investment Trust ",
    # "S7OU.SI": "Asian Pay Television Trust",
    # "TS0U.SI": "OUE Commercial REIT - Real Estate",
    # "U9E.SI": "China Everbright Water Limited",
    # "S8N.SG": "Sembcorp Marine - Marine",
    # "5GZ.SI": "HGH Holdings Ltd.",
    # "RE4.SI": "Geo Energy Resources - Energy",
    # "40T.SI": "ISEC Healthcare Ltd.",
    # "U77.SI": "Sarine Technologies - Technology",
    # "AJ2.SI": "Ouhua Energy Holdings Limited",
    # "1A4.SI": "AGV Group - Industrial",
    # "S41.SI": "Hong Leong Finance Limited",
    # "Q0X.SI": "Ley Choon Group - Construction",
    # "S71.SI": "Sunright Limited",
    # "5UX.SI": "Oxley Holdings - Real Estate",
    # "5IF.SI": "Natural Cool Holdings Limited - Hospitality",
    # "OV8.SI": "Sheng Siong Group - Retail",
    # "AIY.SI": "iFast Corporation - Financial Services",
    # "5CP.SI": "Silverlake Axis - Technology",
    # "P15.SI": "Pacific Century Regional Developments Limited",
    # "5AB.SI": "Trek 2000 International Ltd",
    # "AZI.SI": "AusNet Services - Utilities",
    # "U13.SI": "United Overseas Insurance Limited",
    # "558.SI": "UMS Holdings - Semiconductors",
    # "1D0.SI": "Kimly Limited",
    # "I07.SI": "ISDN Holdings - Industrial Automation",
    # "5UX.SI": "Oxley Holdings Limited",
    # "M35.SI": "Wheelock Properties - Real Estate",
    # "A30.SI": "Aspial Corporation Limited",
    # "5G1.SI": "EuroSports Global Limited",
    # "BJZ.SI": "Koda Ltd - Manufacturing",
    # "5TT.SI": "Keong Hong Holdings Limited",
}

stocks_malaysia = {
    "0001.KL": "Supercomnet Technologies Berhad",
    "0002.KL": "Kotra Industries Berhad",
    "0005.KL": "UCrest Berhad",
    "0006.KL": "Pineapple Resources Berhad",
    "0007.KL": "PUC Berhad",
    "0008.KL": "Willowglen MSC Berhad",
    "0010.KL": "IRIS Corporation Berhad",
    "0011.KL": "Brite-Tech Berhad",
    "0012.KL": "Three-A Resources Berhad",
    "0017.KL": "XOX Technology Berhad",
    "0018.KL": "Lambo Group Berhad",
    "0020.KL": "NetX Holdings Berhad",
    "0022.KL": "Parlo Berhad",
    "0023.KL": "IFCA MSC Berhad",
    "0024.KL": "JAG Berhad",
    "0025.KL": "YBS International Berhad",
    "0026.KL": "Nova MSC Berhad",
    "0026PA.KL": "Nova MSC Berhad",
    "0028.KL": "Scope Industries Berhad",
    "0029.KL": "Digistar Corporation Berhad",
    "0032.KL": "REDtone Digital Berhad",
    "0034.KL": "MMAG Holdings Berhad",
    "0035.KL": "Hextar Capital Berhad",
    "0036.KL": "Key Alliance Group Berhad",
    "0037.KL": "RGB International Bhd.",
    "0038.KL": "Artroniq Berhad",
    "0039.KL": "GFM Services Berhad",
    "0040.KL": "OpenSys (M) Berhad",
    "0041.KL": "Hong Seng Consolidated Berhad",
    "0043.KL": "Metronic Global Berhad",
    "0045.KL": "Southern Score Builders Berhad",
    "0048.KL": "Ancom Logistics Berhad",
    "0049.KL": "Oceancash Pacific Berhad",
    "0050.KL": "Systech Bhd",
    "0051.KL": "Cuscapi Berhad",
    "0053.KL": "OSK Ventures International Berhad",
    "0054.KL": "Karyon Industries Berhad",
    "0055.KL": "Sersol Berhad",
    "0056.KL": "NCT Alliance Berhad",
    "0058.KL": "JcbNext Berhad",
    "0060.KL": "Harvest Miracle Capital Berhad",
    "0064.KL": "Efficient E-Solutions Berhad",
    "0065.KL": "Excel Force MSC Berhad",
    "0066.KL": "Vsolar Group Berhad",
    "0068.KL": "Asdion Berhad",
    "0069.KL": "Vinvest Capital Holdings Berhad",
    "0070.KL": "MQ Technology Berhad",
    "0072.KL": "AT Systematization Berhad",
    "0074.KL": "Green Ocean Corporation Berhad",
    "0075.KL": "LYC Healthcare Berhad",
    "0078.KL": "GDEX Berhad",
    "0079.KL": "Aldrich Resources Berhad",
    "0080.KL": "Straits Energy Resources Berhad",
    "0081.KL": "Rekatech Capital Berhad",
    "0082.KL": "Green Packet Berhad",
    "0083.KL": "Notion VTec Berhad",
    "0084.KL": "Fast Energy Holdings Berhad",
    "0085.KL": "Mlabs Systems Berhad",
    "0086.KL": "Ygl Convergence Berhad",
    "0089.KL": "Tex Cycle Technology (M) Berhad",
    "0090.KL": "Elsoft Research Berhad",
    "0091.KL": "Propel Global Bhd",
    "0092.KL": "mTouche Technology Berhad",
    "0093.KL": "Solution Group Berhad",
    "0094.KL": "Zen Tech International Berhad",
    "0095.KL": "MAG Holdings Berhad",
    "0096.KL": "Nexgram Holdings Berhad",
    "0097.KL": "ViTrox Corporation Berhad",
    "0098.KL": "Bahvest Resources Berhad",
    "0099.KL": "Scicom (MSC) Berhad",
    "0100.KL": "ES Ceramics Technology Berhad",
    "0101.KL": "TMC Life Sciences Berhad",
    "0102.KL": "Waja Konsortium Berhad",
    "0103.KL": "M N C Wireless Berhad",
    "0103PA.KL": "M N C Wireless Berhad",
    "0104.KL": "Genetec Technology Berhad",
    "0105.KL": "Asia Poly Holdings Berhad",
    "0106.KL": "Rexit Berhad",
    "0107.KL": "Eduspec Holdings Berhad",
    "0108.KL": "N2N Connect Berhad",
    "0109.KL": "SC Estate Builder Berhad",
    "0111.KL": "K-One Technology Berhad",
    "0112.KL": "Mikro MSC Berhad",
    "0113.KL": "MMS Ventures Berhad",
    "0116.KL": "Focus Dynamics Group Berhad",
    "0116PA.KL": "Focus Dynamics Group Berhad",
    "0117.KL": "SMRT Holdings Berhad",
    "0118.KL": "Trive Property Group Berhad",
    "0119.KL": "AppAsia Berhad",
    "0120.KL": "Visdynamics Holdings Berhad",
    "0122.KL": "Advance Information Marketing Berhad",
    "0123.KL": "Privasia Technology Berhad",
    "0126.KL": "Microlink Solutions Berhad",
    "0127.KL": "JHM Consolidation Berhad",
    "0128.KL": "Frontken Corporation Berhad",
    "0129.KL": "Silver Ridge Holdings Bhd.",
    "0131.KL": "Divfex Berhad",
    "0132.KL": "Technodex Bhd",
    "0133.KL": "Sanichi Technology Berhad",
    "0136.KL": "Greenyield Berhad",
    "0138.KL": "My E.G. Services Berhad",
    "0140.KL": "Xox Networks Berhad",
    "0143.KL": "Key ASIC Berhad",
    "0145.KL": "TFP Solutions Berhad",
    "0146.KL": "JF Technology Berhad",
    "0147.KL": "Innity Corporation Berhad",
    "0148.KL": "Sunzen Biotech Berhad",
    "0149.KL": "Fibon Berhad",
    "0150.KL": "Fintec Global Berhad",
    "0151.KL": "Kelington Group Berhad",
    "0152.KL": "DGB Asia Berhad",
    "0153.KL": "Oversea Enterprise Berhad",
    "0154.KL": "EA Holdings Berhad",
    "0155.KL": "Malaysian Genomics Resource Centre Berhad",
    "0156.KL": "ManagePay Systems Berhad",
    "0157.KL": "Focus Point Holdings Berhad",
    "0158.KL": "SCC Holdings Berhad",
    "0159.KL": "MMM Group Berhad",
    "0160.KL": "Hiap Huat Holdings Berhad",
    "0161.KL": "Hextar Industries Berhad",
    "0162.KL": "Widad Group Berhad",
    "0163.KL": "Careplus Group Berhad",
    "0165.KL": "XOX Berhad",
    "0166.KL": "Inari Amertron Berhad",
    "0167.KL": "MClean Technologies Berhad",
    "0168.KL": "BM GreenTech Berhad",
    "0169.KL": "SMTrack Berhad",
    "0170.KL": "Kanger International Berhad",
    "0171.KL": "PeterLabs Holdings Berhad",
    "0172.KL": "OCK Group Berhad",
    "0173.KL": "Catcha Digital Berhad",
    "0174.KL": "Evd Berhad",
    "0174PA.KL": "Evd Berhad",
    "0175.KL": "HHRG Berhad",
    "0176.KL": "Kronologi Asia Berhad",
    "0177.KL": "Pasukhas Group Berhad",
    "0178.KL": "Sedania Innovator Berhad",
    "0179.KL": "Bioalpha Holdings Berhad",
    "0179PA.KL": "Bioalpha Holdings Berhad",
    "0180.KL": "Kim Teck Cheong Consolidated Berhad",
    "0181.KL": "Aemulus Holdings Berhad",
    "0182.KL": "LKL International Berhad",
    "0183.KL": "Salutica Berhad",
    "0185.KL": "HSS Engineers Berhad",
    "0186.KL": "Perak Transit Berhad",
    "0187.KL": "BCM Alliance Berhad",
    "0188.KL": "HLT Global Berhad",
    "0189.KL": "Matang Berhad",
    "0190.KL": "Eversafe Rubber Berhad",
    "0191.KL": "Cabnet Holdings Berhad",
    "0192.KL": "Inta Bina Group Berhad",
    "0193.KL": "Kinergy Advancement Berhad",
    "0195.KL": "Binasat Communications Berhad",
    "0196.KL": "QES Group Berhad",
    "0197.KL": "Wegmans Holdings Berhad",
    "0198.KL": "GDB Holdings Berhad",
    "0199.KL": "Tri-Mode System (M) Berhad",
    "0200.KL": "Revenue Group Berhad",
    "0201.KL": "Nova Wellness Group Berhad",
    "0202.KL": "Radiant Globaltech Berhad",
    "0203.KL": "Securemetric Berhad",
    "0205.KL": "DPI Holdings Berhad",
    "0206.KL": "Gagasan Nadi Cergas Berhad",
    "0207.KL": "Mestron Holdings Berhad",
    "0208.KL": "Greatech Technology Berhad",
    "0209.KL": "Aimflex Berhad",
    "0210.KL": "Kim Hin Joo (Malaysia) Berhad",
    "0211.KL": "Tashin Holdings Berhad",
    "0212.KL": "SDS Group Berhad",
    "0213.KL": "MTAG Group Berhad",
    "0215.KL": "Solarvest Holdings Berhad",
    "0216.KL": "Spring Art Holdings Berhad",
    "0217.KL": "Powerwell Holdings Berhad",
    "0218.KL": "ACO Group Berhad",
    "0219.KL": "Reservoir Link Energy Bhd",
    "0220.KL": "Ocean Vantage Holdings Berhad",
    "0221.KL": "TCS Group Holdings Berhad",
    "0222.KL": "Optimax Holdings Berhad",
    "0223.KL": "Samaiden Group Berhad",
    "0225.KL": "Southern Cable Group Berhad",
    "0226.KL": "Aneka Jaringan Holdings Berhad",
    "0227.KL": "Econframe Berhad",
    "0228.KL": "HPP Holdings Berhad",
    "0229.KL": "Mobilia Holdings Berhad",
    "0230.KL": "Teladan Group Berhad",
    "0231.KL": "Flexidynamic Holdings Berhad",
    "0232.KL": "Volcano Berhad",
    "0233.KL": "Pekat Group Berhad",
    "0235.KL": "Nestcon Berhad",
    "0236.KL": "Ramssol Group Berhad",
    "0237.KL": "Haily Group Berhad",
    "0238.KL": "CEKD Berhad",
    "0239.KL": "Ecomate Holdings Berhad",
    "0240.KL": "Coraza Integrated Technology Berhad",
    "0241.KL": "Taghill Holdings Berhad",
    "0242.KL": "Pappajack Berhad",
    "0243.KL": "Cengild Medical Berhad",
    "0245.KL": "MN Holdings Berhad",
    "0246.KL": "Cnergenz Berhad",
    "0247.KL": "Unitrade Industries Berhad",
    "0248.KL": "Yew Lee Pacific Group Berhad",
    "0249.KL": "LGMS Berhad",
    "0250.KL": "YX Precious Metals Bhd",
    "0251.KL": "SFP Tech Holdings Berhad",
    "0252.KL": "Orgabio Holdings Berhad",
    "0253.KL": "Infoline Tec Group Berhad",
    "0255.KL": "Ecoscience International Berhad",
    "0256.KL": "UMediC Group Berhad",
    "0257.KL": "Unique Fire Holdings Berhad",
    "0258.KL": "Agmo Holdings Berhad",
    "0259.KL": "SNS Network Technology Berhad",
    "0260.KL": "PT Resources Holdings Berhad",
    "0261.KL": "Cosmos Technology International Berhad",
    "0262.KL": "Sunview Group Berhad",
    "0263.KL": "Betamek Berhad",
    "0265.KL": "Infomina Berhad",
    "0266.KL": "Leform Berhad",
    "0267.KL": "ECA Integrated Solution Berhad",
    "0268.KL": "L&P Global Berhad",
    "0269.KL": "DS Sigma Holdings Berhad",
    "0270.KL": "NationGate Holdings Berhad",
    "0271.KL": "Wellspire Holdings Berhad",
    "0272.KL": "TT Vision Holdings Berhad",
    "0273.KL": "Vestland Berhad",
    "0275.KL": "Oppstar Berhad",
    "0276.KL": "Autocount Dotcom Berhad",
    "0277.KL": "Cloudpoint Technology Berhad",
    "0278.KL": "Edelteq Holdings Berhad",
    "0279.KL": "Synergy House Berhad",
    "0280.KL": "MYMBN Berhad",
    "0281.KL": "Daythree Digital Berhad",
    "0282.KL": "KGW Group Berhad",
    "0283.KL": "DC Healthcare Holdings Berhad",
    "0284.KL": "Glostrext Berhad",
    "0285.KL": "Mercury Securities Group Berhad",
    "0286.KL": "Evergreen Max Cash Capital Berhad",
    "0287.KL": "SSF Home Group Berhad",
    "0288.KL": "Minox International Group Berhad",
    "0289.KL": "PLYTEC Holding Berhad",
    "0290.KL": "Panda Eco System Berhad",
    "0291.KL": "Critical Holdings Berhad",
    "0292.KL": "Jati Tinggi Group Berhad",
    "0293.KL": "KJTS",
    "0295.KL": "Master Tec Group Berhad",
    "0296.KL": "HE Group Berhad",
    "0297.KL": "TSA",
    "0298.KL": "Wentel Engineering Holdings Berhad",
    "0299.KL": "AGX Group Berhad",
    "0300.KL": "SBH Marine Holdings Berhad",
    "03001.KL": "Cloudaron Group Berhad",
    "0301.KL": "Zantat Holdings Berhad",
    "03016.KL": "Carlo Rino Group Berhad",
    "0302.KL": "Topmix Berhad",
    "03023.KL": "Smile-Link Healthcare Global Berhad",
    "0303.KL": "ALPHA",
    "03036.KL": "RedPlanet Berhad",
    "03038.KL": "ICT Zone Asia Berhad",
    "0304.KL": "Farm Price Holdings Berhad",
    "0305.KL": "Sin-Kung Logistics Berhad",
    "0306.KL": "SMART",
    "0307.KL": "KENERGY",
    "0308.KL": "KTI",
    "0309.KL": "Agricore CS Holdings Berhad",
    "0310.KL": "UUE Holdings Berhad",
    "0311.KL": "Go Hub Capital Berhad",
    "0312.KL": "Ocean Fresh Berhad",
    "0313.KL": "BWYS Group Berhad",
    "0315.KL": "Kucingko Berhad",
    "0316.KL": "Sik Cheong Berhad",
    "0317.KL": "EPB Group Berhad",
    "0318.KL": "Elridge Energy Holdings Berhad",
    "0319.KL": "VETECE Holdings Berhad",
    "0320.KL": "Steel Hawk Berhad",
    "0321.KL": "SDCG",
    "0800EA.KL": "ABF Malaysia Bond Index",
    "0820EA.KL": "FTSE Bursa Malaysia KLCI ETF",
    "0821EA.KL": "Eq8 Dow Jones Islamic Market Malaysia Titans 25 ETF",
    "0822EA.KL": "Principal FTSE ASEAN 40 Malaysia",
    "0823EA.KL": "Principal FTSE China 50 ETF",
    "0824EA.KL": "Eq8 MSCI Malaysia Islamic Dividend ETF",
    "0825EA.KL": "Eq8 MSCI SEA Islamic Dividend ETF",
    "0827EA.KL": "Eq8 Dow Jones US Titans 50 ETF",
    "0828EA.KL": "TradePlus Shariah Gold ETF",
    "0829EA.KL": "TradePlus S&P New China Tracker ETF",
    "0834EA.KL": "Kenanga KLCI Daily 2x Leveraged ETF",
    "0835EA.KL": "Kenanga KLCI Daily (-1x) Inverse ETF",
    "0836EA.KL": "TradePlus DWA Malaysia Momentum Tracker ETF",
    "0837EA.KL": "TradePlus MSCI Asia ex Japan REITs Tracker ETF",
    "0838EA.KL": "VP-DJ Shariah China A-Shares 100 ETF",
    "1015.KL": "AMMB Holdings Berhad",
    "1023.KL": "CIMB Group Holdings Berhad",
    "1058.KL": "Manulife Holdings Berhad",
    "1066.KL": "RHB Bank Berhad",
    "1082.KL": "Hong Leong Financial Group Berhad",
    "1147.KL": "Global Oriental Berhad",
    "1155.KL": "Malayan Banking Berhad",
    "1163.KL": "Allianz Malaysia Berhad",
    "1171.KL": "MBSB Berhad",
    "1198.KL": "MAA Group Berhad",
    "1287.KL": "Pan Malaysia Holdings Berhad",
    "1295.KL": "Public Bank Berhad",
    "1368.KL": "UEM Edgenta Berhad",
    "1481.KL": "Advance Synergy Berhad",
    "1503.KL": "GuocoLand (Malaysia) Berhad",
    "1538.KL": "Symphony Life Berhad",
    "1562.KL": "Sports Toto Berhad",
    "1589.KL": "Iskandar Waterfront City Berhad",
    "1619.KL": "DRB-HICOM Berhad",
    "1643.KL": "Landmarks Berhad",
    "1651.KL": "Malaysian Resources Corporation Berhad",
    "1694.KL": "Menang Corporation (M) Berhad",
    "1724.KL": "Paramount Corporation Berhad",
    "1818.KL": "Bursa Malaysia Berhad",
    "1899.KL": "Batu Kawan Berhad",
    "1902.KL": "Pinehill Pacific Berhad",
    "1929.KL": "Chin Teck Plantations Berhad",
    "1961.KL": "IOI Corporation Berhad",
    "1996.KL": "Kretam Holdings Berhad",
    "2038.KL": "Negri Sembilan Oil Palms Berhad",
    "2054.KL": "TDM Berhad",
    "2062.KL": "Harbour-Link Group Berhad",
    "2089.KL": "United Plantations Berhad",
    "2097.KL": "Meta Bright Group Berhad",
    "2127.KL": "Comfort Gloves Berhad",
    "2135.KL": "Gopeng Berhad",
    "2143.KL": "ECM Libra Group Berhad",
    "2186.KL": "Kuchai Development Berhad",
    "2224.KL": "Selangor Dredging Berhad",
    "2259.KL": "Talam Transform Berhad",
    "2283.KL": "Zelan Berhad",
    "2291.KL": "Genting Plantations Berhad",
    "2305.KL": "AYER Holdings Berhad",
    "2429.KL": "Tanco Holdings Berhad",
    "2445.KL": "Kuala Lumpur Kepong Berhad",
    "2453.KL": "Kluang Rubber Company (Malaya) Berhad",
    "2488.KL": "Alliance Bank Malaysia Berhad",
    "2542.KL": "Riverview Rubber Estates, Berhad",
    "2569.KL": "Sungei Bagan Rubber Company (Malaya) Berhad",
    "2593.KL": "United Malacca Berhad",
    "2607.KL": "Inch Kenneth Kajang Rubber Public Limited Company",
    "2658.KL": "Ajinomoto (Malaysia) Berhad",
    "2674.KL": "Alcom Group Berhad",
    "2682.KL": "Parkwood Holdings Berhad",
    "2739.KL": "Techna-X Berhad",
    "2755.KL": "FCW Holdings Berhad",
    "2828.KL": "C.I. Holdings Berhad",
    "2836.KL": "Carlsberg Brewery Malaysia Berhad",
    "2852.KL": "Cahya Mata Sarawak Berhad",
    "2984.KL": "FACB Industries Incorporated Berhad",
    "3018.KL": "Olympia Industries Berhad",
    "3026.KL": "Dutch Lady Milk Industries Berhad",
    "3034.KL": "Hap Seng Consolidated Berhad",
    "3042.KL": "Petron Malaysia Refining & Marketing Bhd",
    "3069.KL": "Mega First Corporation Berhad",
    "3107.KL": "Fima Corporation Berhad",
    "3158.KL": "YNH Property Bhd",
    "3174.KL": "Land & General Berhad",
    "3182.KL": "Genting Berhad",
    "3204.KL": "George Kent (Malaysia) Berhad",
    "3239.KL": "Berjaya Assets Berhad",
    "3247.KL": "GUH Holdings Berhad",
    "3255.KL": "Heineken Malaysia Berhad",
    "3298.KL": "Hexza Corporation Berhad",
    "3301.KL": "Hong Leong Industries Berhad",
    "3336.KL": "IJM Corporation Berhad",
    "3379.KL": "Insas Berhad",
    "3379PB.KL": "Insas Berhad",
    "3395.KL": "Berjaya Corporation Berhad",
    "3417.KL": "Eastern & Oriental Berhad",
    "3441.KL": "Johan Holdings Berhad",
    "3476.KL": "Keck Seng (Malaysia) Berhad",
    "3514.KL": "Marco Holdings Berhad",
    "3557.KL": "EcoFirst Consolidated Bhd",
    "3565.KL": "WCE Holdings Berhad",
    "3611.KL": "Paragon Globe Berhad",
    "3662.KL": "Malayan Flour Mills Berhad",
    "3689.KL": "Fraser & Neave Holdings Bhd",
    "3719.KL": "Panasonic Manufacturing Malaysia Berhad",
    "3743.KL": "Sunsuria Berhad",
    "3778.KL": "Melewar Industrial Group Berhad",
    "3794.KL": "Malayan Cement Berhad",
    "3816.KL": "MISC Berhad",
    "3859.KL": "Magnum Berhad",
    "3867.KL": "Malaysian Pacific Industries Berhad",
    "3883.KL": "Muda Holdings Berhad",
    "3891.KL": "Malayan United Industries Berhad",
    "3905.KL": "Mulpha International Bhd",
    "3913.KL": "MUI Properties Berhad",
    "3948.KL": "DutaLand Berhad",
    "4006.KL": "Oriental Holdings Berhad",
    "4022.KL": "Maxim Global Berhad",
    "4057.KL": "Asian Pac Holdings Berhad",
    "4065.KL": "PPB Group Berhad",
    "4081.KL": "Pan Malaysia Corporation Berhad",
    "4162.KL": "British American Tobacco (Malaysia) Berhad",
    "4197.KL": "Sime Darby Berhad",
    "4219.KL": "Berjaya Land Berhad",
    "4235.KL": "Lion Industries Corporation Berhad",
    "4243.KL": "W T K Holdings Berhad",
    "4251.KL": "I-Berhad",
    "4286.KL": "Seal Incorporated Berhad",
    "4316.KL": "Sin Heng Chan (Malaya) Berhad",
    "4324.KL": "Hengyuan Refining Company Berhad",
    "4359.KL": "Turiya Berhad",
    "4375.KL": "South Malaysia Industries Berhad",
    "4383.KL": "Jaya Tiasa Holdings Berhad",
    "4405.KL": "Tan Chong Motor Holdings Berhad",
    "4456.KL": "Dagang NeXchange Berhad",
    "4464.KL": "Pegasus Heights Berhad",
    "4502.KL": "Media Prima Berhad",
    "4596.KL": "Sapura Resources Berhad",
    "4634.KL": "Pos Malaysia Berhad",
    "4677.KL": "YTL Corporation Berhad",
    "4707.KL": "Nestlé (Malaysia) Berhad",
    "4715.KL": "Genting Malaysia Berhad",
    "4723.KL": "JAKS Resources Berhad",
    "4731.KL": "Scientex Berhad",
    "4758.KL": "Ancom Nylex Berhad",
    "4847.KL": "Epicon Berhad",
    "4863.KL": "Telekom Malaysia Berhad",
    "4936.KL": "Malpac Holdings Berhad",
    "4995.KL": "Versatile Creative Berhad",
    "5000.KL": "Hume Cement Industries Berhad",
    "5001.KL": "Mieco Chipboard Berhad",
    "5005.KL": "Unisem (M) Berhad",
    "5006.KL": "Varia Berhad",
    "5007.KL": "Chin Well Holdings Berhad",
    "5008.KL": "Harrisons Holdings (Malaysia) Berhad",
    "5009.KL": "White Horse Berhad",
    "5010.KL": "Tong Herr Resources Berhad",
    "5011.KL": "Mesiniaga Berhad",
    "5012.KL": "Ta Ann Holdings Berhad",
    "5014.KL": "Malaysia Airports Holdings Berhad",
    "5015.KL": "APM Automotive Holdings Berhad",
    "5016.KL": "Warisan TC Holdings Berhad",
    "5020.KL": "Glomac Berhad",
    "5021.KL": "AYS Ventures Berhad",
    "5022.KL": "Paos Holdings Berhad",
    "5024.KL": "Hup Seng Industries Berhad",
    "5025.KL": "Auro Holdings Berhad",
    "5026.KL": "MHC Plantations Bhd.",
    "5027.KL": "Kim Loong Resources Berhad",
    "5028.KL": "HeiTech Padu Berhad",
    "5029.KL": "Far East Holdings Berhad",
    "5031.KL": "TIME dotCom Berhad",
    "5032.KL": "Bintulu Port Holdings Berhad",
    "5035.KL": "Knusford Berhad",
    "5036.KL": "Edaran Berhad",
    "5037.KL": "Compugates Holdings Berhad",
    "5038.KL": "KSL Holdings Berhad",
    "5040.KL": "Meridian Berhad",
    "5041.KL": "PBA Holdings Bhd",
    "5042.KL": "TSR Capital Berhad",
    "5048.KL": "YB Ventures Berhad",
    "5049.KL": "Country View Berhad",
    "5053.KL": "OSK Holdings Berhad",
    "5054.KL": "TRC Synergy Berhad",
    "5056.KL": "Engtex Group Berhad",
    "5062.KL": "Hua Yang Berhad",
    "5065.KL": "Ornapaper Berhad",
    "5066.KL": "NTPM Holdings Berhad",
    "5068.KL": "Luster Industries Bhd",
    "5069.KL": "BLD Plantation Bhd.",
    "5070.KL": "Protasco Berhad",
    "5071.KL": "Coastal Contracts Bhd",
    "5072.KL": "Hiap Teck Venture Berhad",
    "5073.KL": "Naim Holdings Berhad",
    "5075.KL": "Plenitude Berhad",
    "5077.KL": "Maybulk Berhad",
    "5078.KL": "Marine & General Berhad",
    "5079.KL": "One Glove Group Berhad",
    "5080.KL": "Poh Kong Holdings Berhad",
    "5081.KL": "Esthetics International Group Berhad",
    "5082.KL": "Annum Berhad",
    "5084.KL": "Ibraco Berhad",
    "5085.KL": "Mudajaya Group Berhad",
    "5087.KL": "Mycron Steel Berhad",
    "5088.KL": "Apex Equity Holdings Berhad",
    "5090.KL": "Media Chinese International Limited",
    "5094.KL": "CSC Steel Holdings Berhad",
    "5095.KL": "HeveaBoard Berhad",
    "5098.KL": "Malaysia Steel Works (KL) Bhd.",
    "5099.KL": "Capital A Berhad",
    "5100.KL": "BP Plastics Holding Bhd.",
    "5101.KL": "Evergreen Fibreboard Berhad",
    "5102.KL": "Guan Chong Berhad",
    "5104.KL": "Citra Nusa Holdings Berhad",
    "5105.KL": "Can-One Berhad",
    "5106.KL": "Axis Real Estate Investment Trust",
    "5108.KL": "icapital biz Bhd",
    "5109.KL": "YTL Hospitality REIT",
    "5110.KL": "Uoa Real Estate Investment",
    "5111.KL": "Tower Real Estate Investment Trust",
    "5112.KL": "TH Plantations Berhad",
    "5113.KL": "Rimbunan Sawit Berhad",
    "5115.KL": "Alam Maritim Resources Berhad",
    "5116.KL": "Al-'Aqar Healthcare REIT",
    "5120.KL": "AmFirst Real Estate Investment Trust",
    "5121.KL": "Hektar Real Estate Investment Trust",
    "5123.KL": "Sentral REIT",
    "5125.KL": "Pantech Group Holdings Berhad",
    "5126.KL": "Sarawak Oil Palms Berhad",
    "5127.KL": "AmanahRaya Real Estate Investment Trust",
    "5130.KL": "Atrium Real Estate Investment Trust",
    "5131.KL": "Zhulian Corporation Berhad",
    "5132.KL": "Deleum Berhad",
    "5133.KL": "Petra Energy Berhad",
    "5134.KL": "Southern Acids (M) Berhad",
    "5135.KL": "Sarawak Plantation Berhad",
    "5136.KL": "Hextar Technologies Solutions Berhad",
    "5138.KL": "Hap Seng Plantations Holdings Berhad",
    "5139.KL": "AEON Credit Service (M) Berhad",
    "5140.KL": "TASCO Berhad",
    "5141.KL": "Dayang Enterprise Holdings Bhd",
    "5142.KL": "Wasco Berhad",
    "5143.KL": "Luxchem Corporation Berhad",
    "5145.KL": "Sealink International Berhad",
    "5147.KL": "Samchem Holdings Berhad",
    "5148.KL": "UEM Sunrise Berhad",
    "5149.KL": "TAS Offshore Berhad",
    "5151.KL": "Hextar Global Berhad",
    "5152.KL": "Muar Ban Lee Group Berhad",
    "5156.KL": "XiDeLang Holdings Ltd",
    "5157.KL": "Saudee Group Berhad",
    "5159.KL": "Yoong Onn Corporation Berhad",
    "5160.KL": "Homeritz Corporation Berhad",
    "5161.KL": "JCY International Berhad",
    "5162.KL": "VSTECS Berhad",
    "5163.KL": "Seremban Engineering Berhad",
    "5165.KL": "DFCITY Group Berhad",
    "5166.KL": "Cyberjaya Education Group Berhad",
    "5168.KL": "Hartalega Holdings Berhad",
    "5169.KL": "Ho Hup Construction Company Berhad",
    "5170.KL": "Sarawak Cable Berhad",
    "5171.KL": "Kimlun Corporation Berhad",
    "5172.KL": "Sinaran Advance Group Berhad",
    "5173.KL": "Shin Yang Group Berhad",
    "5175.KL": "Ivory Properties Group Berhad",
    "5176.KL": "Sunway Real Estate Investment Trust",
    "5178.KL": "Ingenieur Gudang Berhad",
    "5180.KL": "CapitaLand Malaysia Trust",
    "5182.KL": "Avaland Berhad",
    "5183.KL": "PETRONAS Chemicals Group Berhad",
    "5184.KL": "Cypark Resources Berhad",
    "5185.KL": "AFFIN Bank Berhad",
    "5186.KL": "Malaysia Marine and Heavy Engineering Holdings Berhad",
    "5187.KL": "HB Global Limited",
    "5188.KL": "China Ouhua Winery Holdings Limited",
    "5190.KL": "Benalec Holdings Berhad",
    "5191.KL": "Tambun Indah Land Berhad",
    "5192.KL": "K. Seng Seng Corporation Berhad",
    "5195.KL": "Censof Holdings Berhad",
    "5196.KL": "Berjaya Food Berhad",
    "5197.KL": "Focus Lumber Berhad",
    "5199.KL": "Hibiscus Petroleum Berhad",
    "5200.KL": "UOA Development Bhd",
    "5202.KL": "MSM Malaysia Holdings Berhad",
    "5204.KL": "AwanBiru Technology Berhad",
    "5205.KL": "Eversendai Corporation Berhad",
    "5207.KL": "SBC Corporation Berhad",
    "5208.KL": "EITA Resources Berhad",
    "5209.KL": "Gas Malaysia Berhad",
    "5210.KL": "Bumi Armada Berhad",
    "5211.KL": "Sunway Berhad",
    "5211PA.KL": "Sunway Berhad",
    "5212.KL": "Pavilion Real Estate Investment Trust",
    "5213.KL": "Sentoria Group Berhad",
    "5216.KL": "Datasonic Group Berhad",
    "5218.KL": "Sapura Energy Berhad",
    "5219.KL": "Pestech International Berhad",
    "5220.KL": "Globaltec Formation Berhad",
    "5222.KL": "FGV Holdings Berhad",
    "5223.KL": "Mentiga Corporation Berhad",
    "5225.KL": "IHH Healthcare Berhad",
    "5226.KL": "Gabungan AQRS Berhad",
    "5227.KL": "IGB Real Estate Investment Trust",
    "5228.KL": "ELK-Desa Resources Berhad",
    "5230.KL": "Tune Protect Group Berhad",
    "5231.KL": "PBS Berhad",
    "5232.KL": "Leon Fuat Berhad",
    "5235SS.KL": "KLCC Property Holdings Berhad",
    "5236.KL": "Matrix Concepts Holdings Berhad",
    "5237.KL": "MPHB Capital Berhad",
    "5238.KL": "AirAsia X Berhad",
    "5239.KL": "Titijaya Land Berhad",
    "5242.KL": "Solid Automotive Berhad",
    "5243.KL": "Velesto Energy Berhad",
    "5246.KL": "Westports Holdings Berhad",
    "5247.KL": "Karex Berhad",
    "5248.KL": "Bermaz Auto Berhad",
    "5249.KL": "IOI Properties Group Berhad",
    "5250.KL": "7-Eleven Malaysia Holdings Berhad",
    "5252.KL": "Sasbadi Holdings Berhad",
    "5253.KL": "Econpile Holdings Berhad",
    "5255.KL": "Icon Offshore Berhad",
    "5256.KL": "Reach Energy Berhad",
    "5257.KL": "Carimin Petroleum Berhad",
    "5258.KL": "Bank Islam Malaysia Berhad",
    "5259.KL": "E.A. Technique (M) Berhad",
    "5260.KL": "Only World Group Holdings Berhad",
    "5263.KL": "Sunway Construction Group Berhad",
    "5264.KL": "Malakoff Corporation Berhad",
    "5265.KL": "Dolphin International Berhad",
    "5267.KL": "Xin Hwa Holdings Berhad",
    "5269.KL": "Al-Salam Real Estate Investment Trust",
    "5271.KL": "Pecca Group Berhad",
    "5272.KL": "Ranhill Utilities Berhad",
    "5273.KL": "Chin Hin Group Berhad",
    "5274.KL": "Hong Leong Capital Berhad",
    "5275.KL": "Mynews Holdings Berhad",
    "5276.KL": "Dancomech Holdings Berhad",
    "5277.KL": "FoundPac Group Berhad",
    "5278.KL": "Rhone Ma Holdings Berhad",
    "5280.KL": "KIP Real Estate Investment Trust",
    "5281.KL": "Advancecon Holdings Berhad",
    "5283.KL": "Eco World International Berhad",
    "5284.KL": "Lotte Chemical Titan Holding Berhad",
    "5285.KL": "SD Guthrie Berhad",
    "5286.KL": "Mi Technovation Berhad",
    "5288.KL": "Sime Darby Property Berhad",
    "5289.KL": "Techbond Group Berhad",
    "5291.KL": "HPMT Holdings Berhad",
    "5292.KL": "UWC Berhad",
    "5293.KL": "AME Elite Consortium Berhad",
    "5295.KL": "InNature Berhad",
    "5296.KL": "Mr D.I.Y. Group (M) Berhad",
    "5297.KL": "Tuju Setia Berhad",
    "5298.KL": "OM Holdings Limited",
    "5299.KL": "IGB Commercial Real Estate Investment Trust",
    "5300.KL": "Yenher Holdings Berhad",
    "5301.KL": "CTOS Digital Berhad",
    "5302.KL": "Aurelius Technologies Berhad",
    "5303.KL": "Swift Haulage Berhad",
    "5305.KL": "Senheng New Retail Berhad",
    "5306.KL": "Farm Fresh Berhad",
    "5307.KL": "AME Real Estate Investment Trust",
    "5308.KL": "Seng Fong Holdings Berhad",
    "5309.KL": "ITMAX System Berhad",
    "5310.KL": "Kumpulan Kitacon Berhad",
    "5311.KL": "Cape EMS Berhad",
    "5313.KL": "Radium Development Berhad",
    "5315.KL": "SkyWorld Development Berhad",
    "5316.KL": "MST Golf Group Berhad",
    "5317.KL": "CPE Technology Berhad",
    "5318.KL": "DXN Holdings Bhd.",
    "5319.KL": "MKH Oil Palm (East Kalimantan) Berhad",
    "5320.KL": "PLINTAS",
    "5321.KL": "Keyfield International Berhad",
    "5322.KL": "Feytech Holdings Berhad",
    "5323.KL": "JPG",
    "5325.KL": "Well Chip Group Berhad",
    "5326.KL": "99 Speed Mart Retail Holdings Berhad",
    "5347.KL": "Tenaga Nasional Berhad",
    "5371.KL": "Kim Hin Industry Berhad",
    "5398.KL": "Gamuda Berhad",
    "5401.KL": "Tropicana Corporation Berhad",
    "5436.KL": "Perusahaan Sadur Timah Malaysia (Perstima) Berhad",
    "5517.KL": "Shangri-La Hotels (Malaysia) Berhad",
    "5533.KL": "OCB Berhad",
    "5568.KL": "APB Resources Berhad",
    "5576.KL": "Minho (M) Berhad",
    "5592.KL": "Grand Central Enterprises Bhd.",
    "5606.KL": "IGB Berhad",
    "5614.KL": "ILB Group Berhad",
    "5622.KL": "Pimpinan Ehsan Berhad",
    "5649.KL": "Golden Pharos Berhad",
    "5657.KL": "Parkson Holdings Berhad",
    "5665.KL": "Southern Steel Berhad",
    "5673.KL": "Jentayu Sustainables Berhad",
    "5681.KL": "PETRONAS Dagangan Berhad",
    "5703.KL": "Muhibbah Engineering (M) Bhd.",
    "5738.KL": "Country Heights Holdings Berhad",
    "5789.KL": "LBS Bina Group Berhad",
    "5797.KL": "Choo Bee Metal Industries Berhad",
    "5819.KL": "Hong Leong Bank Berhad",
    "5827.KL": "Oriental Interest Berhad",
    "5843.KL": "Kumpulan Perangsang Selangor Berhad",
    "5878.KL": "KPJ Healthcare Berhad",
    "5908.KL": "DKSH Holdings (Malaysia) Berhad",
    "5916.KL": "Malaysia Smelting Corporation Berhad",
    "5932.KL": "Bina Puri Holdings Bhd",
    "5983.KL": "MBM Resources Berhad",
    "6009.KL": "Pacific & Orient Berhad",
    "6012.KL": "Maxis Berhad",
    "6017.KL": "SHL Consolidated Bhd.",
    "6033.KL": "PETRONAS Gas Berhad",
    "6041.KL": "Farlim Group (Malaysia) Bhd.",
    "6068.KL": "PCCS Group Berhad",
    "6076.KL": "Encorp Berhad",
    "6084.KL": "Star Media Group Berhad",
    "6114.KL": "MKH Berhad",
    "6139.KL": "Syarikat Takaful Malaysia Keluarga Berhad",
    "6173.KL": "Bina Darulaman Berhad",
    "6181.KL": "Malton Berhad",
    "6203.KL": "Khee San Berhad",
    "6211.KL": "Kia Lim Berhad",
    "6254.KL": "PDZ Holdings Bhd",
    "6262.KL": "Innoprise Plantations Berhad",
    "6297.KL": "Box-Pak (Malaysia) Bhd.",
    "6351.KL": "Amway (Malaysia) Holdings Berhad",
    "6378.KL": "WMG Holdings Bhd.",
    "6399.KL": "Astro Malaysia Holdings Berhad",
    "6432.KL": "Apollo Food Holdings Berhad",
    "6459.KL": "MNRB Holdings Berhad",
    "6483.KL": "Kenanga Investment Bank Berhad",
    "6491.KL": "Kumpulan Fima Berhad",
    "6521.KL": "Suria Capital Holdings Berhad",
    "6556.KL": "Ann Joo Resources Berhad",
    "6556PA.KL": "Ann Joo Resources Berhad",
    "6599.KL": "Aeon Co. (M) Bhd.",
    "6602.KL": "BCB Berhad",
    "6633.KL": "Leong Hup International Berhad",
    "6637.KL": "PNE PCB Berhad",
    "6718.KL": "Crescendo Corporation Berhad",
    "6742.KL": "YTL Power International Berhad",
    "6769.KL": "JKG Land Berhad",
    "6807.KL": "Puncak Niaga Holdings Berhad",
    "6815.KL": "Eupe Corporation Berhad",
    "6874.KL": "KUB Malaysia Berhad",
    "6888.KL": "Axiata Group Berhad",
    "6904.KL": "Subur Tiasa Holdings Berhad",
    "6912.KL": "Pasdec Holdings Berhad",
    "6939.KL": "Fiamma Holdings Berhad",
    "6947.KL": "Celcomdigi Berhad",
    "6963.KL": "V.S. Industry Berhad",
    "6971.KL": "Kobay Technology Bhd.",
    "6998.KL": "Bintai Kinden Corporation Berhad",
    "7004.KL": "MCE Holdings Berhad",
    "7005.KL": "B.I.G. Industries Berhad",
    "7006.KL": "Rhong Khen International Berhad",
    "7007.KL": "ARK Resources Holdings Berhad",
    "7010.KL": "PTT Synergy Group Berhad",
    "7013.KL": "Hubline Berhad",
    "7014.KL": "YLI Holdings Berhad",
    "7016.KL": "Chuan Huat Resources Berhad",
    "7017.KL": "Komarkcorp Berhad",
    "7020.KL": "ASTEEL Group Berhad",
    "7022.KL": "Globetronics Technology Bhd.",
    "7025.KL": "Woodlandor Holdings Berhad",
    "7028.KL": "Zecon Berhad",
    "7029.KL": "Master-Pack Group Berhad",
    "7031.KL": "Amtel Holdings Berhad",
    "7033.KL": "Kumpulan H & L High-Tech Berhad",
    "7034.KL": "Thong Guan Industries Berhad",
    "7035.KL": "CCK Consolidated Holdings Berhad",
    "7036.KL": "Borneo Oil Berhad",
    "7043.KL": "Xin Synergy Group Berhad",
    "7047.KL": "Fajarbaru Builder Group Bhd.",
    "7048.KL": "Atlan Holdings Bhd",
    "7050.KL": "Wong Engineering Corporation Berhad",
    "7052.KL": "Padini Holdings Berhad",
    "7054.KL": "Astral Asia Berhad",
    "7055.KL": "PLB Engineering Berhad",
    "7060.KL": "New Hoong Fatt Holdings Berhad",
    "7062.KL": "Khind Holdings Berhad",
    "7066.KL": "Yong Tai Berhad",
    "7070.KL": "Vizione Holdings Berhad",
    "7071.KL": "OCR Group Berhad",
    "7073.KL": "Seacera Group Berhad",
    "7076.KL": "CB Industrial Product Holding Berhad",
    "7077.KL": "Kerjaya Prospek Property Berhad",
    "7078.KL": "Ahmad Zaki Resources Berhad",
    "7079.KL": "TWL Holdings Berhad",
    "7080.KL": "Permaju Industries Berhad",
    "7081.KL": "Pharmaniaga Berhad",
    "7082.KL": "M & A Equity Holdings Berhad",
    "7083.KL": "Analabs Resources Berhad",
    "7084.KL": "QL Resources Berhad",
    "7085.KL": "LTKM Berhad",
    "7086.KL": "AbleGroup Berhad",
    "7087.KL": "Magni-Tech Industries Berhad",
    "7088.KL": "Poh Huat Resources Holdings Berhad",
    "7089.KL": "Lii Hen Industries Bhd",
    "7090.KL": "Apex Healthcare Berhad",
    "7091.KL": "Unimech Group Berhad",
    "7094.KL": "Eurospan Holdings Berhad",
    "7095.KL": "P.I.E. Industrial Berhad",
    "7096.KL": "Joe Holding Berhad",
    "7097.KL": "Ta Win Holdings Berhad",
    "7099.KL": "Mayu Global Group Berhad",
    "7100.KL": "Uchi Technologies Berhad",
    "7103.KL": "Spritzer Bhd",
    "7105.KL": "HCK Capital Group Berhad",
    "7106.KL": "Supermax Corporation Berhad",
    "7107.KL": "Oriental Food Industries Holdings Berhad",
    "7108.KL": "Perdana Petroleum Berhad",
    "7113.KL": "Top Glove Corporation Bhd.",
    "7114.KL": "D'nonce Technology Bhd.",
    "7115.KL": "SKB Shutters Corporation Berhad",
    "7117.KL": "CJ Century Logistics Holdings Berhad",
    "7120.KL": "Axteria Group Berhad",
    "7121.KL": "XL Holdings Berhad",
    "7123.KL": "Maxland Berhad",
    "7128.KL": "CAM Resources Berhad",
    "7129.KL": "Asia File Corporation Bhd.",
    "7130.KL": "Reneuco Berhad",
    "7131.KL": "ACME Holdings Berhad",
    "7132.KL": "SMIS Corporation Berhad",
    "7133.KL": "United U-LI Corporation Berhad",
    "7134.KL": "PWF Corporation Bhd.",
    "7137.KL": "UMS Holdings Berhad",
    "7139.KL": "Niche Capital Emas Holdings Berhad",
    "7140.KL": "OKA Corporation Bhd",
    "7145.KL": "Ageson Berhad",
    "7145PA.KL": "Ageson Berhad",
    "7146.KL": "AE Multi Holdings Berhad",
    "7148.KL": "Duopharma Biotech Berhad",
    "7152.KL": "Jaycorp Berhad",
    "7153.KL": "Kossan Rubber Industries Bhd",
    "7154.KL": "Classita Holdings Berhad",
    "7155.KL": "SKP Resources Bhd",
    "7157.KL": "CYL Corporation Berhad",
    "7160.KL": "Pentamaster Corporation Berhad",
    "7161.KL": "Kerjaya Prospek Group Berhad",
    "7162.KL": "Astino Berhad",
    "7163.KL": "PJBumi Berhad",
    "7164.KL": "KNM Group Berhad",
    "7165.KL": "Velocity Capital Partner Berhad",
    "7167.KL": "Able Global Berhad",
    "7168.KL": "PRG Holdings Berhad",
    "7169.KL": "Dominant Enterprise Berhad",
    "7170.KL": "LFE Corporation Berhad",
    "7172.KL": "PMB Technology Berhad",
    "7173.KL": "Toyo Ventures Holdings Berhad",
    "7174.KL": "CAB Cakaran Corporation Berhad",
    "7176.KL": "TPC Plus Berhad",
    "7178.KL": "Y.S.P. Southeast Asia Holding Berhad",
    "7179.KL": "Lagenda Properties Berhad",
    "7180.KL": "Sern Kou Resources Berhad",
    "7181.KL": "ARB Berhad",
    "7184.KL": "G3 Global Berhad",
    "7186.KL": "SWS Capital Berhad",
    "7187.KL": "Chin Hin Group Property Berhad",
    "7188.KL": "BTM Resources Berhad",
    "7191.KL": "Adventa Berhad",
    "7192.KL": "GIIB Holdings Berhad",
    "7195.KL": "Binastra Corporation Berhad",
    "7197.KL": "GE-Shen Corporation Berhad",
    "7198.KL": "DPS Resources Berhad",
    "7199.KL": "Kein Hing International Berhad",
    "7200.KL": "Tek Seng Holdings Berhad",
    "7201.KL": "Progressive Impact Corporation Berhad",
    "7202.KL": "Hextar Retail Berhad",
    "7203.KL": "Wang-Zheng Berhad",
    "7204.KL": "D & O Green Technologies Berhad",
    "7207.KL": "Success Transformer Corporation Berhad",
    "7208.KL": "Euro Holdings Berhad",
    "7209.KL": "Cheetah Holdings Berhad",
    "7210.KL": "FM Global Logistics Holdings Berhad",
    "7211.KL": "TAFI Industries Berhad",
    "7212.KL": "Destini Berhad",
    "7214.KL": "A-Rank Berhad",
    "7215.KL": "Ni Hsin Group Berhad",
    "7215PA.KL": "Ni Hsin Group Berhad",
    "7216.KL": "Kawan Food Berhad",
    "7217.KL": "Eonmetall Group Berhad",
    "7218.KL": "Arka Berhad",
    "7219.KL": "AIZO Group Berhad",
    "7219PA.KL": "AIZO Group Berhad",
    "7221.KL": "BSL Corporation Berhad",
    "7222.KL": "Imaspro Corporation Berhad",
    "7223.KL": "Jadi Imaging Holdings Berhad",
    "7225.KL": "P.A. Resources Berhad",
    "7226.KL": "Watta Holding Berhad",
    "7227.KL": "UMS-Neiken Group Berhad",
    "7228.KL": "T7 Global Berhad",
    "7229.KL": "Favelle Favco Berhad",
    "7230.KL": "Tomei Consolidated Berhad",
    "7231.KL": "Wellcall Holdings Berhad",
    "7232.KL": "Resintech Berhad",
    "7233.KL": "Dufu Technology Corp. Berhad",
    "7234.KL": "MESB Berhad",
    "7235.KL": "Superlon Holdings Berhad",
    "7237.KL": "Power Root Berhad",
    "7239.KL": "Scanwolf Corporation Berhad",
    "7240.KL": "Infraharta Holdings Berhad",
    "7241.KL": "Nextgreen Global Berhad",
    "7243.KL": "Magma Group Berhad",
    "7245.KL": "Citaglobal Berhad",
    "7246.KL": "Signature International Berhad",
    "7247.KL": "SCGM Bhd",
    "7248.KL": "SLP Resources Berhad",
    "7249.KL": "Skygate Solutions Berhad",
    "7250.KL": "Uzma Berhad",
    "7251.KL": "Barakah Offshore Petroleum Berhad",
    "7252.KL": "Teo Seng Capital Berhad",
    "7253.KL": "Handal Energy Berhad",
    "7277.KL": "Dialog Group Berhad",
    "7285.KL": "Tomypak Holdings Berhad",
    "7293.KL": "Yinson Holdings Berhad",
    "7315.KL": "AHB Holdings Berhad",
    "7323.KL": "Ken Holdings Berhad",
    "7374.KL": "Tien Wah Press Holdings Berhad",
    "7412.KL": "SHH Resources Holdings Berhad",
    "7439.KL": "Teck Guan Perdana Berhad",
    "7471.KL": "Eden Inc. Berhad",
    "7498.KL": "Ralco Corporation Berhad",
    "7501.KL": "Harn Len Corporation Bhd",
    "7544.KL": "Quality Concrete Holdings Berhad",
    "7579.KL": "AWC Berhad",
    "7595.KL": "MGB Berhad",
    "7609.KL": "Ajiya Berhad",
    "7617.KL": "Magna Prima Berhad",
    "7668.KL": "Beshom Holdings Berhad",
    "7676.KL": "G Capital Berhad",
    "7692.KL": "MyTech Group Berhad",
    "7722.KL": "Asia Brands Berhad",
    "7757.KL": "UPA Corporation Berhad",
    "7765.KL": "Rapid Synergy Berhad",
    "7773.KL": "EP Manufacturing Bhd",
    "7803.KL": "Hextar Healthcare Berhad",
    "7811.KL": "Sapura Industrial Berhad",
    "7854.KL": "Timberwell Berhad",
    "7889.KL": "Thriven Global Berhad",
    "7935.KL": "Milux Corporation Berhad",
    "7943.KL": "Mpire Global Berhad",
    "7986.KL": "CN Asia Corporation Bhd",
    "8044.KL": "Computer Forms (Malaysia) Berhad",
    "8052.KL": "Central Global Berhad",
    "8079.KL": "Lee Swee Kiat Group Berhad",
    "8117.KL": "PGF Capital Berhad",
    "8125.KL": "Scientex Packaging (Ayer Keroh) Berhad",
    "8133.KL": "Boustead Heavy Industries Corporation Berhad",
    "8141.KL": "Majuperak Holdings Berhad",
    "8176.KL": "ATA IMS Berhad",
    "8192.KL": "Mercury Industries Berhad",
    "8206.KL": "Eco World Development Group Berhad",
    "8273.KL": "Public Packages Holdings Berhad",
    "8303.KL": "Lotus KFM Berhad",
    "8311.KL": "Pesona Metro Holdings Berhad",
    "8338.KL": "Dataprep Holdings Bhd",
    "8346.KL": "Perak Corporation Berhad",
    "8362.KL": "KYM Holdings Bhd",
    "8397.KL": "Tiong Nam Logistics Holdings Berhad",
    "8419.KL": "Pansar Berhad",
    "8419PA.KL": "Pansar Berhad",
    "8435.KL": "Concrete Engineering Products Berhad",
    "8443.KL": "Hil Industries Berhad",
    "8478.KL": "Hwa Tai Industries Berhad",
    "8486.KL": "Lion Posim Berhad",
    "8494.KL": "LBI Capital Berhad",
    "8524.KL": "Taliworks Corporation Berhad",
    "8532.KL": "Pertama Digital Berhad",
    "8567.KL": "Salcon Berhad",
    "8583.KL": "Mah Sing Group Berhad",
    "8591.KL": "Crest Builder Holdings Berhad",
    "8605.KL": "Federal International Holdings Berhad",
    "8613.KL": "ENRA Group Berhad",
    "8621.KL": "LPI Capital Bhd",
    "8648.KL": "Jasa Kita Berhad",
    "8664.KL": "S P Setia Berhad",
    "8664PA.KL": "S P Setia Berhad",
    "8664PC.KL": "S P Setia Berhad",
    "8672.KL": "Kamdar Group (M) Berhad",
    "8702.KL": "Texchem Resources Bhd",
    "8745.KL": "S & F Capital Berhad",
    "8834.KL": "Ireka Corporation Berhad",
    "8869.KL": "Press Metal Aluminium Holdings Berhad",
    "8877.KL": "Ekovest Berhad",
    "8885.KL": "Avillion Berhad",
    "8893.KL": "M K Land Holdings Berhad",
    "8907.KL": "EG Industries Berhad",
    "8923.KL": "Jiankun International Berhad",
    "8966.KL": "Techbase Industries Berhad",
    "8982.KL": "Cepatwawasan Group Berhad",
    "9008.KL": "Omesti Berhad",
    "9008PB.KL": "Omesti Berhad",
    "9059.KL": "TSH Resources Berhad",
    "9075.KL": "Theta Edge Berhad",
    "9083.KL": "Kumpulan Jetson Berhad",
    "9091.KL": "Emico Holdings Berhad",
    "9113.KL": "Iconic Worldwide Berhad",
    "9121.KL": "KPS Consortium Berhad",
    "9148.KL": "Greater Bay Holdings Berhad",
    "9172.KL": "Formosa Prosonic Industries Berhad",
    "9199.KL": "Lysaght Galvanized Steel Berhad",
    "9237.KL": "Sarawak Consolidated Industries Berhad",
    "9261.KL": "Gadang Holdings Berhad",
    "9288.KL": "Bonia Corporation Berhad",
    "9296.KL": "RCE Capital Berhad",
    "9318.KL": "FITTERS Diversified Berhad",
    "9326.KL": "LB Aluminium Berhad",
    "9334.KL": "KESM Industries Berhad",
    "9369.KL": "Teo Guan Lee Corporation Berhad",
    "9377.KL": "FSBM Holdings Berhad",
    "9385.KL": "Lay Hong Berhad",
    "9393.KL": "Industronics Berhad",
    "9407.KL": "Paragon Union Berhad",
    "9423.KL": "CWG Holdings Berhad",
    "9423R1.KL": "CWG-R1",
    "9431.KL": "Seni Jaya Corporation Berhad",
    "9466.KL": "KKB Engineering Berhad",
    "9539.KL": "Multi-Usage Holdings Berhad",
    "9571.KL": "Mitrajaya Holdings Berhad",
    "9598.KL": "Pintaras Jaya Berhad",
    "9601.KL": "Ho Wah Genting Berhad",
    "9679.KL": "WCT Holdings Berhad",
    "9687.KL": "Ideal Capital Berhad",
    "9695.KL": "PLS Plantations Berhad",
    "9717.KL": "Sycal Ventures Berhad",
    "9741.KL": "Rohas Tecnic Berhad",
    "9776.KL": "Sinmah Capital Berhad",
    "9792.KL": "SEG International Bhd",
    "9814.KL": "Bertam Alliance Berhad",
    "9822.KL": "SAM Engineering & Equipment (M) Berhad",
    "9873.KL": "Prestar Resources Berhad",
    "9881.KL": "Leader Steel Holdings Berhad",
    "9938.KL": "Bright Packaging Industry Berhad",
    "9946.KL": "Rex Industry Berhad",
    "9954.KL": "RGT Berhad",
    "9962.KL": "Gromutual Berhad",
    "9997.KL": "Pensonic Holdings Berhad",
}

# =========================
# ===== US Stocks =====
# =========================
stocks_us = {
    # --- Core Growth / Trend Amplifiers ---
    "MSFT": "Microsoft",
    "AAPL": "Apple",
    "GOOGL": "Alphabet (Google)",
    "META": "Meta Platforms",
    "AMZN": "Amazon",
    "NVDA": "NVIDIA",
    "TSLA": "Tesla",
    # --- Financial / Rate Sensitive ---
    "JPM": "JPMorgan Chase",
    "BAC": "Bank of America",
    # --- Defensive / Slow Trend ---
    "JNJ": "Johnson & Johnson",
    "PG": "Procter & Gamble",
    "KO": "Coca-Cola",
    "MCD": "McDonald's",
    # --- Quality Tech ---
    "ADBE": "Adobe",
    "NVO": "Novo Nordisk",
}

# =========================
# ===== Index ETFs =====
# =========================
index_etfs = {
    # --- US Core ---
    "SPY": "SPDR S&P 500 ETF",
    "VOO": "Vanguard S&P 500 ETF",
    "QQQ": "Invesco Nasdaq-100 ETF",
    # --- Factor / High Volatility ---
    "SPMO": "S&P 500 Momentum ETF",
    "ARKK": "ARK Innovation ETF",
    # --- Non-US / Regional ---
    "EWJ": "iShares MSCI Japan ETF",
    "EWG": "iShares MSCI Germany ETF",
    "EEM": "iShares MSCI Emerging Markets ETF",
}

# =========================
# ===== Bonds / Macro Anchors =====
# =========================
bonds_macro = {
    "TLT": "20+ Year Treasury Bond ETF",
    "IEF": "7-10 Year Treasury Bond ETF",
    "SHY": "1-3 Year Treasury Bond ETF",
    "TIP": "Treasury Inflation-Protected Securities ETF",
    "LQD": "Investment Grade Corporate Bond ETF",
}

# =========================
# ===== Futures / Commodities =====
# =========================
futures = {
    # --- Energy ---
    "CL=F": "Crude Oil",
    # --- Precious Metals ---
    "GC=F": "Gold",
    "SI=F": "Silver",
    # --- Industrial Metals ---
    "HG=F": "Copper",
    "ZN=F": "Zinc",
    # --- Agriculture ---
    "ZS=F": "Soybeans",
    "ZW=F": "Wheat",
    "ZC=F": "Corn",
    # --- Equity Index ---
    "ES=F": "S&P 500 E-mini Futures",
    # --- FX Futures ---
    "6E=F": "Euro FX Futures",
    "6J=F": "Japanese Yen FX Futures",
    "DX=F": "US Dollar Index Futures",
}

# =========================
# ===== High Risk / Leveraged =====
# =========================
high_risk = {
    "SOXL": "Direxion Daily Semiconductor Bull 3X",
}

# =========================
# ===== China / HK =====
# =========================
china_hk = {
    "BABA": "Alibaba Group",
    "0700.HK": "Tencent Holdings",
    "0981.HK": "SMIC",
    "0763.HK": "ZTE",
}

# =========================
# ===== FX / Crypto / SG =====
# =========================
fx_crypto = {
    # --- FX ---
    "UUP": "US Dollar Index ETF",
    # --- Crypto ---
    "TON-USD": "Toncoin",
    "NEAR-USD": "NEAR Protocol",
    "BTC-USD": "Bitcoin",
    "ETH-USD": "ETH",
    "XRP-USD": "XRP",
    "ADA-USD": "ADA",
    "SOL-USD": "SOL",
    "LINK-USD": "Chainlink",
    "ARB-USD": "Arbitrum",
    "RNDR-USD": "Render GPU",
    "HNT-USD": "Helium",
}

# =========================
# ===== Merge All =====
# =========================
symbols_map = {}
symbols_map.update(stocks_us)
symbols_map.update(index_etfs)
symbols_map.update(bonds_macro)
symbols_map.update(futures)
symbols_map.update(high_risk)
symbols_map.update(china_hk)
symbols_map.update(fx_crypto)

watching_list = list(symbols_map.keys())


def fast_scanning():
    market_client = MarketClient(init_log=True)
    list_obj = market_client.get_market_tickers()
    symbols = []
    for obj in list_obj:
        amount = obj.amount
        count = obj.count
        open = obj.open
        close = obj.close
        low = obj.low
        high = obj.high
        vol = obj.vol
        symbol = obj.symbol
        bid = obj.bid
        bidSize = obj.bidSize
        ask = obj.ask
        askSize = obj.askSize
        if amount * close >= 10000000:
            # if vol >= 5000000:
            symbols.append(symbol)
    print(f"Available: {len(symbols)}")
    return symbols


def download_data(IMarketSensorImp, ccy, interval, sample, show=False):
    overrides = {
        "interval": interval,
        "funds": 100,
        "stake_cap": 100,
        "symbol": Symbol(ccy),
        "hmm_split": 4,
        "api_key": api_key,
        "secret_key": secret_key,
        "atr_loss_margin": 1.2,
        "hmm_model": "trend",
    }

    sp = pandas_util.build_strategy_param(overrides)
    camp = HuntingCamp(sp, IMarketSensorImp(symbol=sp.symbol, interval=interval))
    base_df = camp.update()
    camp.save(base_df)

    import time

    time.sleep(3)
    return base_df


def chart(df, code):
    # Ensure the index is of type DatetimeIndex
    if not isinstance(df.index, pd.DatetimeIndex):
        df["Date"] = pd.to_datetime(df["Date"])
        df.set_index("Date", inplace=True)
        df.index = pd.to_datetime(df.index)

    # Create columns for scatter plots with NaN where there's no marker
    obv_up_marker = np.where(df["OBV_UP"], df["OBV"], np.nan)
    close_up_marker = np.where(df["OBV_UP"], df["Close"], np.nan)

    # Prepare additional plots
    add_plots = [
        mpf.make_addplot(
            df["OBV"], panel=1, color="g", secondary_y=False, ylabel="OBV"
        ),
        mpf.make_addplot(df["upper_bound"], panel=1, color="gray", linestyle="--"),
        mpf.make_addplot(df["lower_bound"], panel=1, color="gray", linestyle="--"),
        mpf.make_addplot(
            obv_up_marker,
            panel=1,
            type="scatter",
            markersize=100,
            marker="^",
            color="red",
        ),
        mpf.make_addplot(
            close_up_marker, type="scatter", markersize=100, marker="^", color="y"
        ),
    ]

    # Create a candlestick chart with additional plots
    mpf.plot(
        df,
        type="candle",
        addplot=add_plots,
        title=f"{stocks_malaysia.get(code, code)} Price and OBV with Bounds",
        ylabel="Price (USD)",
        style="yahoo",
        datetime_format="%Y-%m-%d %H:%M:%S",
    )


@click.command()
@click.option(
    "--market",
    type=click.Choice(["my", "sg", "crypto", "watching"]),
    required=True,
    help="选择市场类型",
)
@click.option("--symbol", default=None, help="指定交易对或股票代码")
@click.option(
    "--interval",
    default="1day",
    help="交易间隔: 1min, 5min, 15min, 30min, 60min, 4hour, 1day, 1mon, 1week, 1year",
)
@click.option("--show", is_flag=False, help="是否显示图表")
@click.option("--backtest", is_flag=False, help="是否进行回测")
def main(market, symbol, interval, show, backtest):
    if market in ("my", "sg", "watching"):
        sensor_cls = YahooMarketSensor
        if symbol:
            symbols = [symbol]
        else:
            if market == "watching":
                symbols = watching_list
            else:
                symbols = (
                    stocks_malaysia.keys()
                    if market == "my"
                    else stocks_singapore.keys()
                )
        sample = 365 * 20  # 20 years
    elif market == "crypto":
        sensor_cls = HuobiMarketSensor
        # symbols = [symbol] if symbol else fast_scanning()
        symbols = [
            "dogeusdt",
            "nftusdt",
            "kiteusdt",
            "bobbscusdt",
            "linkusdt",
            "trxusdt",
            "ethusdt",
            "btcusdt",
            "wmtxusdt",
            "xdcusdt",
            "bchusdt",
            "daiusdt",
            "fartcoinusdt",
            "chzusdt",
            "apepeusdt",
            "xlmusdt",
            "usdcusdt",
            "monadusdt",
            "xrpusdt",
            "xautusdt",
            "adausdt",
            "filusdt",
            "ltcusdt",
            "wbtusdt",
            "bnbusdt",
            "pepeusdt",
            "suiusdt",
            "hbarusdt",
            "tonusdt",
            "usdqusdt",
            "solusdt",
        ]
        sample = 240 * 3  # 3 years

    from pprint import pprint

    pprint(symbols)
    symbols_count = {
        s: download_data(sensor_cls, s, interval, sample, show) for s in symbols
    }

    if backtest:
        perform_backtest(symbols, interval)


def perform_backtest(symbols, interval):
    result = {}
    for code in symbols:
        print(f"GO [{code} {interval}]")
        overrides = {
            "interval": interval,
            "funds": 100,
            "stake_cap": 100,
            "symbol": Symbol(code),
            "hmm_split": 4,
            "api_key": api_key,
            "secret_key": secret_key,
            "atr_loss_margin": 1.2,
            "hmm_model": "trend",
        }

        sp = pandas_util.build_strategy_param(overrides)
        sensor = LocalMarketSensor(symbol=sp.symbol, interval=sp.interval)
        base_df = sensor.scan(1000)
        scout = TurtleScout(params=sp, buy_signal_func=buy_signal_from_mosaic_strategy)
        base_df = scout.train(base_df)
        try:
            while sensor.left():
                base_df = sensor.fetch(base_df)
                base_df = scout.market_recon(base_df)

            csv_path = f"{config.reports_dir}/{sp}.csv"
            base_df["symbol"] = code
            base_df[DUMP_COL].to_csv(csv_path, index=False)
            # base_df[int(len(base_df) / 2) :][DUMP_COL].to_csv(csv_path, index=False)
            print(f"CSV created: {csv_path}")
        except Exception as e:
            print(f"[{code}] not running correctly: {e}")


def performance_review(backtest_results):
    # 将数据转换为 DataFrame
    df = pd.DataFrame(list(backtest_results.items()), columns=["Stock", "Return"])
    df.to_csv(f"{REPORTS_DIR}/backtest.csv", index=False)
    df = df[df.Return != 0]
    print(df[:60])

    # 总体表现
    average_return = df["Return"].mean()
    total_return = df["Return"].sum()

    # 风险分析
    std_dev = df["Return"].std()
    max_drawdown = df["Return"].min()

    # 胜率分析
    positive_returns = df[df["Return"] > 0].shape[0]
    negative_returns = df[df["Return"] < 0].shape[0]
    win_rate = positive_returns / df.shape[0]
    loss_rate = negative_returns / df.shape[0]

    # Sharpe Ratio
    risk_free_rate = 0.0
    sharpe_ratio = (df["Return"].mean() - risk_free_rate) / df["Return"].std()

    # Sortino Ratio
    negative_returns = df[df["Return"] < 0]["Return"]
    downside_std = negative_returns.std()
    sortino_ratio = (df["Return"].mean() - risk_free_rate) / downside_std

    # 打印结果
    print(f"Sharpe Ratio: {sharpe_ratio:.2f}")
    print(f"Sortino Ratio: {sortino_ratio:.2f}")

    # 打印结果
    print(f"平均回报率: {average_return:.2f}%")
    print(f"总回报率: {total_return:.2f}%")
    print(f"回报率标准差: {std_dev:.2f}%")
    print(f"最大回撤: {max_drawdown:.2f}%")
    print(f"胜率: {win_rate:.2f}")
    print(f"失败率: {loss_rate:.2f}")

    # 绘制收益分布图
    plt.figure(figsize=(14, 8))
    sns.histplot(df["Return"], bins=20, kde=True, color="blue")
    plt.title("Distribution of Returns")
    plt.xlabel("Return (%)")
    plt.ylabel("Frequency")
    plt.show()


if __name__ == "__main__":
    # result = {code: entry(code, "1day", 100, 50) for code in stocks_malaysia.keys()}
    # from pprint import pprint

    # pprint(result)
    main()
